* Translated Variable Labels for RAIS_2012.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "पीआईएस/पीएएसईपी रजिस्ट्री में कर्मचारी पंजीकरण संख्या"
label variable CPF "कार्यकर्ता का सी.पी.एफ"
label variable numectps "श्रमिक का CTPS नंबर"
label variable nome "कार्यकर्ता का नाम"
label variable identificad "प्रतिष्ठान का सीएनपीजे या सीईआई (अग्रणी शून्य के बिना)"
label variable radiccnpj "प्रतिष्ठान के सीएनपीजे का रेडिकल (8 स्थान, बाईं ओर शून्य के बिना)"
label variable municipio "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable tpvinculo "रोजगार संबंध का प्रकार"
label variable empem3112 "12/31 पर सक्रिय लिंक संकेतक (1 - हाँ; 0 - नहीं)"
label variable tipoadm "टिपोएडम का रिकोड (प्रवेश प्रकार)"
label variable dtadmissao "कर्मचारी के प्रवेश की तिथि (पूर्ण)"
label variable causadesli "शटडाउन का कारण"
label variable mesdesli "कर्मचारी समाप्ति का महीना"
label variable ocup2002 "सीबीओ (व्यवसायों का ब्राज़ीलियाई वर्गीकरण), 2002 में बनाया गया (6 अंक)"
label variable grinstrucao "शिक्षा की डिग्री"
label variable genero "लिंग"
label variable idade "आयु"
label variable nacionalidad "राष्ट्रीयता"
label variable portdefic "कोई विकलांगता नहीं है"
label variable tpdefic "विकलांगता का प्रकार"
label variable raca_cor "कार्यकर्ता की जाति और रंग"
label variable sbclas20 "CNAE 2.0 वर्गीकरण के अनुसार आर्थिक गतिविधि समूह"
label variable clascnae95 "सीएनएई कक्षा 1.0 (प्रतिष्ठान की मुख्य गतिविधि)"
label variable clascnae20 "सीएनएई कक्षा 2.0 (प्रतिष्ठान की मुख्य गतिविधि)"
label variable tamestab "प्रतिष्ठान का आकार - 12/31 पर सक्रिय कर्मचारी"
label variable natjuridica "प्रतिष्ठान की कानूनी प्रकृति"
label variable tipoestbl "रिपोर्टिंग प्रतिष्ठान का प्रकार (सीएनपीजे, सीईआई, पहचाना नहीं गया या अनदेखा किया गया)"
label variable remdezembro "दिसंबर में श्रमिकों का पारिश्रमिक, न्यूनतम मजदूरी में"
label variable remdezr "दिसंबर में औसत कर्मचारी पारिश्रमिक, नाममात्र मूल्य में"
label variable remmedia "न्यूनतम वेतन में वर्ष का औसत वेतन"
label variable remmedr "नाममात्र मूल्य में वर्ष का औसत वेतन"
label variable tempempr "कर्मचारी के रोजगार की अवधि महीनों में (जब संचित होती है, तो योग का प्रतिनिधित्व करती है"
label variable tiposal "संविदा वेतन का प्रकार"
label variable salcontr "कर्मचारी का संविदात्मक वेतन, नाममात्र मूल्य में"
label variable ultrem ""
label variable horascontr "प्रति सप्ताह संविदात्मक घंटों की संख्या"
label variable indceivinc "लिंक्ड सीईआई के साथ स्थापना संकेतक"
label variable ceivinc "लिंक्ड सीईआई नंबर, यदि कोई हो"
label variable indalvara "न्यायिक परमिट के साथ कार्यकर्ता संकेतक"
label variable indpat "पीएटी से संबंधित स्थापना का सूचक"
label variable indsimples "सरल विकल्प सूचक"
label variable ocupacao94 "सीबीओ 94 व्यवसाय"
label variable qtdiasafas "दूर दिनों की संख्या"
label variable anochegbr "ब्राज़ील में आगमन का वर्ष"
label variable causafast1 "आधार वर्ष में कर्मचारी की प्रथम अनुपस्थिति का कारण"
label variable causafast2 "आधार वर्ष में कर्मचारी की दूसरी बार अनुपस्थिति का कारण"
label variable causafast3 "आधार वर्ष में कर्मचारी की तीसरी अनुपस्थिति का कारण"
label variable diainiaf1 "पहली छुट्टी की आरंभ तिथि"
label variable diainiaf2 "दूसरी छुट्टी की आरंभ तिथि"
label variable diainiaf3 "तीसरी छुट्टी का शुरुआती दिन"
label variable diafimaf1 "पहली छुट्टी की अंतिम तिथि"
label variable diafimaf2 "दूसरी छुट्टी की अंतिम तिथि"
label variable diafimaf3 "तीसरी छुट्टी का अंतिम दिन"
label variable mesiniaf1 "पहली छुट्टी शुरू होने का महीना"
label variable mesiniaf2 "दूसरी छुट्टी शुरू होने का महीना"
label variable mesiniaf3 "तीसरी छुट्टी प्रारम्भ होने का महीना"
label variable mesfimaf1 "पहली छुट्टी ख़त्म होने का महीना"
label variable mesfimaf2 "दूसरी छुट्टी ख़त्म होने का महीना"
label variable mesfimaf3 "तीसरी छुट्टी ख़त्म होने का महीना"
