* Translated Variable Labels for data_judges_characteristics.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "न्यायाधीश"
label variable gender "लिंग"
label variable race "दौड़"
label variable birth_year "जन्म वर्ष"
label variable education ""
label variable educ_basic "बेसिक तक"
label variable educ_hs "हाई स्कूल"
label variable educ_college "कॉलेज"
label variable educ_grad "ग्रेजुएट स्कूल"
label variable first_year_RAIS "RAIS में प्रथम वर्ष"
label variable first_year_RAIS_public "सार्वजनिक नौकरी में प्रथम वर्ष"
label variable first_year_RAIS_jud "न्यायपालिका की नौकरी में प्रथम वर्ष"
label variable first_wage_RAIS "RAIS में पहला वेतन (R$ 2017)"
label variable prior_wage_bef_public "सार्वजनिक नौकरी से पहले वेतन (R$ 2017)"
label variable prior_wage_bef_jud "न्यायपालिका की नौकरी से पहले वेतन (R$ 2017)"
label variable avg_wage_bef_public "सार्वजनिक नौकरी से पहले औसत वेतन (R$ 2017)"
label variable avg_wage_bef_jud "न्यायपालिका की नौकरी से पहले औसत वेतन (R$ 2017)"
label variable first_munic_RAIS "RAIS में पहली नगर पालिका"
label variable first_munic_public "सार्वजनिक नौकरी में प्रथम नगर पालिका"
label variable first_munic_jud "न्यायपालिका की नौकरी में प्रथम नगर पालिका"
