* Translated Variable Labels for RAIS_1992-2017_estab_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable id_firm "Radical du CNPJ de l'establishment (8 positions, sans zéros à gauche)"
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year "Année"
label variable size_estab "Taille de l'établissement"
label variable type_estab "Type d'établissement"
label variable legal_nature "Nature fraîche"
label variable cnae1 "CNAE 1.0"
label variable sector1 "Secteur Économique 1.0 (IBGE)"
label variable sector "Secteur"
label variable public "Publique"
label variable public_federal "Public Fédéral"
label variable public_state "État public"
label variable public_municipal "Public Municipal"
label variable public_exec "Exécutif public"
label variable public_leg "Législative publique"
label variable public_jud "Pouvoir judiciaire public"
label variable company "Entreprise"
label variable company_public "Entreprise publique"
label variable nonprofit "Non lucratif"
label variable cnae2 "CNAE 2.0"
label variable sector2 "Secteur Économique 2.0 (IBGE)"
