* Translated Variable Labels for RAIS_workers_BL_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "Numéro d’inscription du salarié au registre PIS/PASEP"
label variable id_estab "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year "Année"
label variable type_contract "Type de contrat"
label variable type_admission "Type d'admission"
label variable hours "Heures embauchées"
label variable type_wage "Type de salaire"
label variable hired_wage "Salaire embauché"
label variable last_wage "Dernier salaire"
label variable employed_3112 "En poste au 31 décembre"
label variable ym_admission "Admission année-mois"
label variable year_admission "Année d'admission"
label variable month_admission "Mois d'admission"
label variable ym_separation "Séparation Année-Mois"
label variable month_separation "Mois de séparation"
label variable cause_separation "Cause de séparation"
label variable time_emp "Équipe employée"
label variable hired "Embauché au cours de l'année"
label variable laid_off "Mis à pied au cours de l'année"
label variable n_months "Nombre de mois travaillés"
label variable wage_avg "Salaire mensuel (R$)"
label variable wage_dec "Salaire de décembre (R$)"
label variable wage_total "Salaire annuel total ($ R$)"
label variable wage_avg_def "Salaire mensuel (R$ 2017)"
label variable wage_dec_def "Salaire de décembre (R$ 2017)"
label variable wage_total_def "Salaire annuel total (R$ 2017)"
label variable job_public "Emploi public"
label variable job_public_com "Emploi public commandé"
label variable CBO1994 "CBO (Classification Brésilienne des Professions), créée en 1994"
label variable CBO2002 "CBO (Classification Brésilienne des Professions), créée en 2002 (6 chiffres)"
label variable occup_cat "Catégorie professionnelle (CBO2002)"
label variable education "niveau d'éducation"
label variable gender "Genre"
label variable age "Âge"
label variable nationality "Nationalité"
label variable race "Course"
label variable has_disability "A un handicap"
label variable disability "Invalidité"
