* Translated Variable Labels for data_TSE_RAIS_sample5_1992-2017_worker.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "Número de registro de empleado en el Registro PIS/PASEP"
label variable id_worker_CPF "CPF del trabajador"
label variable id_estab "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable id_munic_6 "Municipio donde está ubicado el establecimiento"
label variable year ""
label variable empem3112 "Indicador de enlace activo el 31/12 (1 - sí; 0 - no)"
label variable tpvinculo "Tipo de relación laboral"
label variable causadesli "Causa del cierre"
label variable mesdesli "Mes de despido del empleado"
label variable ocupacao94 "CBO (Clasificación Brasileña de Ocupaciones), creada en 1994"
label variable mesadmissao "Mes de contratación del trabajador"
label variable remdezembro "Remuneración de los trabajadores en diciembre, en salarios mínimos"
label variable remmedia "Salario promedio del año en salarios mínimos"
label variable tempempr "La duración del empleo del trabajador en meses (cuando se acumula, representa la suma de"
label variable job_public "Trabajo publico"
label variable job_public_com "Trabajo público por encargo"
label variable horascontr "Número de horas contractuales por semana"
label variable tipoadm "Tipo de admisión"
label variable remdezr "Remuneración media de los trabajadores en diciembre, en valor nominal"
label variable remmedr "Salario medio del año en valor nominal"
label variable dtadmissao "Fecha de ingreso del trabajador (Completo)"
label variable tiposal "Tipo de Salario Contractual"
label variable salcontr "El salario contractual del trabajador, en valor nominal"
label variable ultrem ""
label variable id_politician "Político de identificación"
label variable ran_1996 "Corrió 1996"
label variable ran_1998 "Corrió 1998"
label variable ran_2000 "Corrió 2000"
label variable ran_2002 "Corrió 2002"
label variable ran_2004 "Corrió 2004"
label variable ran_2006 "Corrió 2006"
label variable ran_2008 "Corrió 2008"
label variable ran_2010 "Corrió 2010"
label variable ran_2012 "Corrió 2012"
label variable ran_2014 "Corrió 2014"
label variable ran_2016 "Corrió 2016"
label variable ran_2018 "Corrió 2018"
label variable office_1996 "Oficina 1996"
label variable office_1998 "Oficina 1998"
label variable office_2000 "oficina 2000"
label variable office_2002 "Oficina 2002"
label variable office_2004 "Oficina 2004"
label variable office_2006 "Oficina 2006"
label variable office_2008 "Oficina 2008"
label variable office_2010 "Oficina 2010"
label variable office_2012 "Oficina 2012"
label variable office_2014 "Oficina 2014"
label variable office_2016 "Oficina 2016"
label variable office_2018 "Oficina 2018"
label variable elected_1996 "Elegido en 1996"
label variable elected_1998 "Elegido en 1998"
label variable elected_2000 "Elegido en 2000"
label variable elected_2002 "Elegido en 2002"
label variable elected_2004 "Elegido en 2004"
label variable elected_2006 "Elegido en 2006"
label variable elected_2008 "Elegido en 2008"
label variable elected_2010 "Elegido en 2010"
label variable elected_2012 "Elegido en 2012"
label variable elected_2014 "Elegido en 2014"
label variable elected_2016 "Elegido en 2016"
label variable elected_2018 "Elegido 2018"
