* Translated Variable Labels for RAIS_2004.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Employee registration number in the PIS/PASEP Registry"
label variable CPF "worker's CPF"
label variable numectps "Worker's CTPS number"
label variable nome "Worker's name"
label variable identificad "CNPJ or CEI of the establishment (without leading zeros)"
label variable radiccnpj "Radical of the establishment's CNPJ (8 positions, without zeros on the left)"
label variable municipio "Municipality where the establishment is located"
label variable tpvinculo "Type of employment relationship"
label variable empem3112 "Active link indicator on 12/31 (1 - yes; 0 - no)"
label variable tipoadm "RECODE oftipoadm (TYPE ADM)"
label variable dtadmissao "Date of admission of the worker (Complete)"
label variable causadesli "Cause of shutdown"
label variable diadesli "Worker dismissal day"
label variable mesdesli "Month of employee termination"
label variable ocupacao94 "CBO (Brazilian Classification of Occupations), created in 1994"
label variable ocup2002 "CBO (Brazilian Classification of Occupations), created in 2002 (6 digits)"
label variable grinstrucao "Degree of instruction"
label variable genero "Gender"
label variable dtnascimento "Worker's date of birth"
label variable nacionalidad "Nationality"
label variable portdefic "Does not have a disability"
label variable raca_cor "Race and color of the worker"
label variable remdezembro "Workers' remuneration in December, in minimum wages"
label variable remdezr "Average worker remuneration in December, in nominal value"
label variable remmedia "Average salary for the year in minimum wages"
label variable remmedr "Average salary for the year in nominal value"
label variable tempempr "The worker's length of employment in months (when accumulated, represents the sum of"
label variable tiposal "Type of Contract Salary"
label variable salcontr "The worker's contractual salary, in nominal value"
label variable ultrem ""
label variable horascontr "Number of contractual hours per week"
label variable clascnae95 "CNAE Class 1.0 (main activity of the establishment)"
label variable tamestab "Establishment size - Active employees on 12/31"
label variable natjuridica "Legal nature of the establishment"
label variable tipoestbl "Type of reporting establishment (CNPJ, CEI, Not Identified or Ignored)"
label variable indceivinc "Establishment indicator with linked CEI"
label variable ceivinc "Linked CEI number, if any"
label variable indalvara "Worker indicator with Judicial Permit"
label variable indpat "Indicator of establishment belonging to PAT"
label variable indsimples "SIMPLES opting indicator"
