* Translated Variable Labels for RAIS_1988.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Employee registration number in the PIS/PASEP Registry"
label variable identificad "CNPJ or CEI of the establishment (without leading zeros)"
label variable radiccnpj "Radical of the establishment's CNPJ (8 positions, without zeros on the left)"
label variable municipio "Municipality where the establishment is located"
label variable uf "Federation unity"
label variable tpvinculo "Type of employment relationship"
label variable sitvinculo "Bond Status"
label variable empem3112 "Active link indicator on 12/31 (1 - yes; 0 - no)"
label variable anoadm "Admission Year"
label variable mesadmissao "Month of hire of the worker"
label variable causadesli "Cause of shutdown"
label variable mesdesli "Month of employee termination"
label variable ocupacao94 "CBO (Brazilian Classification of Occupations), created in 1994"
label variable grinstrucao "Degree of instruction"
label variable genero "Gender"
label variable faixaetaria "Age Range"
label variable nacionalidad "Nationality"
label variable remdezembro "Workers' remuneration in December, in minimum wages"
label variable remmedia "Average salary for the year in minimum wages"
label variable tempempr "The worker's length of employment in months (when accumulated, represents the sum of"
label variable tamestab "Establishment size - Active employees on 12/31"
label variable tipoestbl "Type of reporting establishment (CNPJ, CEI, Not Identified or Ignored)"
label variable ibgesubsetor "IBGE subsector of the establishment"
label variable ibgeatividade "IBGE activity of the establishment"
label variable bairrossp "SP neighborhoods"
label variable distritossp "SP Districts"
