* Translated Variable Labels for RAIS_2017.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Employee registration number in the PIS/PASEP Registry"
label variable CPF "worker's CPF"
label variable numectps "Worker's CTPS number"
label variable nome "Worker's name"
label variable identificad "CNPJ or CEI of the establishment (without leading zeros)"
label variable radiccnpj "Radical of the establishment's CNPJ (8 positions, without zeros on the left)"
label variable municipio "Municipality where the establishment is located"
label variable tpvinculo "Type of employment relationship"
label variable empem3112 "Active link indicator on 12/31 (1 - yes; 0 - no)"
label variable tipoadm "RECODE oftipoadm (Admission Type)"
label variable dtadmissao "Date of admission of the worker (Complete)"
label variable causadesli "Cause of shutdown"
label variable mesdesli "Month of employee termination"
label variable diadesli "Worker dismissal day"
label variable ocupacao94 "CBO (Brazilian Classification of Occupations), created in 1994"
label variable ocup2002 "CBO (Brazilian Classification of Occupations), created in 2002 (6 digits)"
label variable grinstrucao "Degree of instruction"
label variable genero "Gender"
label variable dtnascimento "Worker's date of birth"
label variable idade "Worker's age"
label variable nacionalidad "Nationality"
label variable portdefic "Does not have a disability"
label variable tpdefic "Type of disability"
label variable raca_cor "Race and color of the worker"
label variable remdezembro "Workers' remuneration in December, in minimum wages"
label variable remmedia "Average salary for the year in minimum wages"
label variable remdezr "Average worker remuneration in December, in nominal value"
label variable remmedr "Average salary for the year in nominal value"
label variable tempempr "The worker's length of employment in months (when accumulated, represents the sum of"
label variable tiposal "Type of Contract Salary"
label variable salcontr "The worker's contractual salary, in nominal value"
label variable ultrem "Last remuneration received by the worker, in nominal value"
label variable horascontr "Number of contractual hours per week"
label variable sbclas20 "Economic activity group, according to CNAE 2.0 classification"
label variable clascnae95 "CNAE Class 1.0 (main activity of the establishment)"
label variable clascnae20 "CNAE Class 2.0 (main activity of the establishment)"
label variable tamestab "Establishment size - Active employees on 12/31"
label variable natjuridica "Legal nature of the establishment"
label variable tipoestbl "Type of reporting establishment (CNPJ, CEI, Not Identified or Ignored)"
label variable indceivinc "Establishment indicator with linked CEI"
label variable ceivinc "Linked CEI number, if any"
label variable indalvara "Worker indicator with Judicial Permit"
label variable indpat "Indicator of establishment belonging to PAT"
label variable indsimples "SIMPLES opting indicator"
label variable qtdiasafas "Number of days away"
label variable ibgesubsetor "IBGE subsector"
label variable anochegbr "Year of arrival in Brazil"
label variable cepestab "Establishment zip code"
label variable muntrab "Worker's municipality"
label variable razaosocial "Corporate name of the establishment"
label variable indtrabparc "Partial work indicator"
label variable indtrabint "Intermittent work indicator"
label variable indsindic "Unionization indicator"
label variable remjan "Average worker remuneration in January, in nominal value"
label variable remfev "Average worker remuneration in February, in nominal value"
label variable remmar "Average worker remuneration in March, in nominal value"
label variable remabr "Average worker remuneration in April, in nominal value"
label variable remmai "Average worker remuneration in May, in nominal value"
label variable remjun "Average worker remuneration in June, in nominal value"
label variable remjul "Average worker remuneration in July, in nominal value"
label variable remago "Average worker remuneration in August, in nominal value"
label variable remset "Average worker remuneration in September, in nominal value"
label variable remout "Average worker remuneration in October, in nominal value"
label variable remnov "Average worker remuneration in November, in nominal value"
label variable causafast1 "Cause of the worker's first absence in the base year"
label variable causafast2 "Cause of the worker's second absence in the base year"
label variable causafast3 "Cause of the worker's third absence in the base year"
label variable diainiaf1 "Start date of first leave"
label variable diainiaf2 "Start date of the second leave"
label variable diainiaf3 "Starting day of the third leave"
label variable diafimaf1 "End date of first leave"
label variable diafimaf2 "End date of second leave"
label variable diafimaf3 "End day of third leave"
label variable mesiniaf1 "Month of start of first leave"
label variable mesiniaf2 "Month of start of second leave"
label variable mesiniaf3 "Month of start of third leave"
label variable mesfimaf1 "Month of end of first leave"
label variable mesfimaf2 "Month of end of second leave"
label variable mesfimaf3 "Month of end of third leave"
