* Translated Variable Labels for RAIS_1992-2017_estab_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable id_firm "Radical del CNPJ del establishment (8 posiciones, sin ceros a la izquierda)"
label variable id_munic_6 "Municipio donde está ubicado el establecimiento"
label variable year "Año"
label variable size_estab "Tamaño del establecimiento"
label variable type_estab "Tipo de establecimiento"
label variable legal_nature "Naturaleza fresca"
label variable cnae1 "CNAE 1.0"
label variable sector1 "Sector Económico 1.0 (IBGE)"
label variable sector "Sector"
label variable public "Público"
label variable public_federal "Público Federal"
label variable public_state "Estado público"
label variable public_municipal "Público Municipal"
label variable public_exec "Ejecutivo Público"
label variable public_leg "Público Legislativo"
label variable public_jud "Poder Judicial Público"
label variable company "Compañía"
label variable company_public "Compañía publica"
label variable nonprofit "Sin ánimo de lucro"
label variable cnae2 "CNAE 2.0"
label variable sector2 "Sector Económico 2.0 (IBGE)"
