* Translated Variable Labels for RAIS_workers_matched_BL_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "Número de registro de empleado en el Registro PIS/PASEP"
label variable id_estab "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable id_munic_6 "Municipio donde está ubicado el establecimiento"
label variable year "Año"
label variable type_contract "tipo de contrato"
label variable type_admission "Tipo de admisión"
label variable hours "Horas contratadas"
label variable type_wage "Tipo de salario"
label variable hired_wage "Salario contratado"
label variable last_wage "último salario"
label variable employed_3112 "Empleado el 31 de diciembre"
label variable ym_admission "Admisión Año-Mes"
label variable year_admission "Año de admisión"
label variable month_admission "Mes de admisión"
label variable ym_separation "Separación Año-Mes"
label variable month_separation "Mes de separación"
label variable cause_separation "Causa de separación"
label variable time_emp "Equipo empleado"
label variable hired "Contratado durante el año"
label variable laid_off "Despedido durante el año"
label variable n_months "Número de meses trabajados"
label variable wage_avg "Salario mensual (R$)"
label variable wage_dec "Salario de diciembre (R$)"
label variable wage_total "Salario total anual (R$)"
label variable wage_avg_def "Salario mensual (R$ 2017)"
label variable wage_dec_def "Salario de diciembre (R$ 2017)"
label variable wage_total_def "Salario total anual (R$ 2017)"
label variable job_public "Trabajo publico"
label variable job_public_com "Trabajo público por encargo"
label variable CBO1994 "CBO (Clasificación Brasileña de Ocupaciones), creada en 1994"
label variable CBO2002 "CBO (Clasificación Brasileña de Ocupaciones), creada en 2002 (6 dígitos)"
label variable occup_cat "Categoría de ocupación (CBO2002)"
label variable education "Nivel de Educación"
label variable gender "Género"
label variable age "Edad"
label variable nationality "Nacionalidad"
label variable race "Carrera"
label variable has_disability "Tiene discapacidad"
label variable disability "Discapacidad"
