* Translated Variable Labels for data_TSE_RAIS_sample5_1992-2017_worker.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "Employee registration number in the PIS/PASEP Registry"
label variable id_worker_CPF "worker's CPF"
label variable id_estab "CNPJ or CEI of the establishment (without leading zeros)"
label variable id_munic_6 "Municipality where the establishment is located"
label variable year ""
label variable empem3112 "Active link indicator on 12/31 (1 - yes; 0 - no)"
label variable tpvinculo "Type of employment relationship"
label variable causadesli "Cause of shutdown"
label variable mesdesli "Month of employee termination"
label variable ocupacao94 "CBO (Brazilian Classification of Occupations), created in 1994"
label variable mesadmissao "Month of hire of the worker"
label variable remdezembro "Workers' remuneration in December, in minimum wages"
label variable remmedia "Average salary for the year in minimum wages"
label variable tempempr "The worker's length of employment in months (when accumulated, represents the sum of"
label variable job_public "Public Job"
label variable job_public_com "Commissioned Public Job"
label variable horascontr "Number of contractual hours per week"
label variable tipoadm "Type of admission"
label variable remdezr "Average worker remuneration in December, in nominal value"
label variable remmedr "Average salary for the year in nominal value"
label variable dtadmissao "Date of admission of the worker (Complete)"
label variable tiposal "Type of Contract Salary"
label variable salcontr "The worker's contractual salary, in nominal value"
label variable ultrem ""
label variable id_politician "ID Politician"
label variable ran_1996 "Ran 1996"
label variable ran_1998 "Ran 1998"
label variable ran_2000 "Ran 2000"
label variable ran_2002 "Ran 2002"
label variable ran_2004 "Ran 2004"
label variable ran_2006 "Ran 2006"
label variable ran_2008 "Ran 2008"
label variable ran_2010 "Ran 2010"
label variable ran_2012 "Ran 2012"
label variable ran_2014 "Ran 2014"
label variable ran_2016 "Ran 2016"
label variable ran_2018 "Ran 2018"
label variable office_1996 "Office 1996"
label variable office_1998 "Office 1998"
label variable office_2000 "Office 2000"
label variable office_2002 "Office 2002"
label variable office_2004 "Office 2004"
label variable office_2006 "Office 2006"
label variable office_2008 "Office 2008"
label variable office_2010 "Office 2010"
label variable office_2012 "Office 2012"
label variable office_2014 "Office 2014"
label variable office_2016 "Office 2016"
label variable office_2018 "Office 2018"
label variable elected_1996 "Elected 1996"
label variable elected_1998 "Elected 1998"
label variable elected_2000 "Elected 2000"
label variable elected_2002 "Elected 2002"
label variable elected_2004 "Elected 2004"
label variable elected_2006 "Elected 2006"
label variable elected_2008 "Elected 2008"
label variable elected_2010 "Elected 2010"
label variable elected_2012 "Elected 2012"
label variable elected_2014 "Elected 2014"
label variable elected_2016 "Elected 2016"
label variable elected_2018 "Elected 2018"
