* Translated Variable Labels for data_judges_characteristics.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "juez"
label variable gender "Género"
label variable race "Carrera"
label variable birth_year "Año de nacimiento"
label variable education ""
label variable educ_basic "Hasta básico"
label variable educ_hs "escuela secundaria"
label variable educ_college "Colega"
label variable educ_grad "Escuela de posgrado"
label variable first_year_RAIS "Primer año en RAIS"
label variable first_year_RAIS_public "Primer año en el empleo público"
label variable first_year_RAIS_jud "Primer año en el puesto judicial"
label variable first_wage_RAIS "Primer Salario en RAIS (R$ 2017)"
label variable prior_wage_bef_public "Salario previo al empleo público (R$ 2017)"
label variable prior_wage_bef_jud "Salario previo al empleo judicial (R$ 2017)"
label variable avg_wage_bef_public "Salario promedio antes del empleo público (R$ 2017)"
label variable avg_wage_bef_jud "Salario promedio antes del trabajo judicial (R$ 2017)"
label variable first_munic_RAIS "Primer Municipio en RAIS"
label variable first_munic_public "Primer Municipio en Empleo Público"
label variable first_munic_jud "Primer Municipio en Empleo Judicial"
