* Translated Variable Labels for data_judges_employment_history_deidentified.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "juez"
label variable name "juez"
label variable state_1_worked_from_CNJ ""
label variable state_2_worked_from_CNJ ""
label variable state_3_worked_from_CNJ ""
label variable id_worker_CTPS "Trabajador de identificación - CTPS"
label variable id_munic_6 "Municipio donde está ubicado el establecimiento"
label variable year "Año"
label variable CBO1994 "CBO (Clasificación Brasileña de Ocupaciones), creada en 1994"
label variable time_emp "Equipo empleado"
label variable hours "Horas contratadas"
label variable type_admission "Tipo de admisión"
label variable employed_3112 "Empleado el 31 de diciembre"
label variable year_admission "Año de admisión"
label variable month_admission "Mes de admisión"
label variable month_separation "Mes de separación"
label variable ym_admission "Admisión Año-Mes"
label variable ym_separation "Separación Año-Mes"
label variable hired "Contratado durante el año"
label variable laid_off "Despedido durante el año"
label variable n_months "Número de meses trabajados"
label variable type_contract "tipo de contrato"
label variable cause_separation "Causa de separación"
label variable wage_avg "Salario mensual (R$)"
label variable wage_dec "Salario de diciembre (R$)"
label variable wage_total "Salario total anual (R$)"
label variable wage_avg_def "Salario mensual (R$ 2017)"
label variable wage_dec_def "Salario de diciembre (R$ 2017)"
label variable wage_total_def "Salario total anual (R$ 2017)"
label variable job_public "Trabajo publico"
label variable job_public_com "Trabajo público por encargo"
label variable CBO2002 "OBC 2002"
label variable occup_cat "Categoría de ocupación (CBO2002)"
label variable size_estab "Tamaño del establecimiento"
label variable type_estab "Tipo de establecimiento"
label variable legal_nature "Naturaleza fresca"
label variable cnae1 "CNAE 1.0"
label variable sector1 "Sector Económico 1.0 (IBGE)"
label variable sector "Sector"
label variable public "Público"
label variable public_federal "Público Federal"
label variable public_state "Estado público"
label variable public_municipal "Público Municipal"
label variable public_exec "Ejecutivo Público"
label variable public_leg "Público Legislativo"
label variable public_jud "Poder Judicial Público"
label variable company "Compañía"
label variable company_public "Compañía publica"
label variable nonprofit "Sin ánimo de lucro"
label variable education "Nivel de Educación"
label variable gender "Género"
label variable age "Edad"
label variable nationality "Nacionalidad"
label variable type_wage "Tipo de salario"
label variable hired_wage "Salario contratado"
label variable last_wage "último salario"
label variable has_disability "Tiene discapacidad"
label variable race "Carrera"
label variable cnae2 "CNAE 2.0"
label variable sector2 "Sector Económico 2.0 (IBGE)"
label variable disability "Discapacidad"
