* Translated Variable Labels for RAIS_1985-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Municipio donde está ubicado el establecimiento"
label variable year "Año"
label variable n_jobs "Trabajos"
label variable n_educ_workers "Número de trabajadores de la educación"
label variable n_health_workers "Número de trabajadores de la salud"
label variable n_estab "Establecimientos"
label variable wage_total_def "Salarios (R$ 2018)"
label variable n_jobs_np "Empleos sin fines de lucro"
label variable wage_total_def_np "Salarios sin fines de lucro (R$ 2018)"
label variable n_jobs_priv "Trabajos privados"
label variable wage_total_def_priv "Salarios privados (R$ 2018)"
label variable n_jobs_pub_fed_exec "Empleos Públicos Ejecutivos Federales"
label variable wage_total_def_pub_fed_exec "Salarios Públicos del Ejecutivo Federal (R$ 2018)"
label variable n_jobs_pub_fed_jud "Empleos Públicos Judiciales Federales"
label variable wage_total_def_pub_fed_jud "Salarios Públicos del Poder Judicial Federal (R$ 2018)"
label variable n_jobs_pub_fed_leg "Empleos Públicos Legislativos Federales"
label variable wage_total_def_pub_fed_leg "Salarios Públicos Legislativos Federales (R$ 2018)"
label variable n_jobs_pub_mun_exec "Empleos Públicos Ejecutivos Municipales"
label variable wage_total_def_pub_mun_exec "Salarios Públicos Ejecutivos Municipales (R$ 2018)"
label variable n_jobs_pub_mun_jud "Empleos Públicos Judiciales Municipales"
label variable wage_total_def_pub_mun_jud "Salarios Públicos del Poder Judicial Municipal (R$ 2018)"
label variable n_jobs_pub_mun_leg "Empleos Públicos Legislativos Municipales"
label variable wage_total_def_pub_mun_leg "Salarios Públicos Legislativos Municipales (R$ 2018)"
label variable n_jobs_pub_stt_exec "Empleos Públicos Ejecutivos Estatales"
label variable wage_total_def_pub_stt_exec "Salarios Públicos del Ejecutivo Estatal (R$ 2018)"
label variable n_jobs_pub_stt_jud "Empleos Públicos Judiciales Estatales"
label variable wage_total_def_pub_stt_jud "Salarios Públicos del Poder Judicial del Estado (R$ 2018)"
label variable n_jobs_pub_stt_leg "Empleos públicos legislativos estatales"
label variable wage_total_def_pub_stt_leg "Salario Público Legislativo Estatal (R$ 2018)"
