* Translated Variable Labels for RAIS_1995-2018_collapsed_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Municipio donde se encuentra el establecimiento"
label variable year "Año"
label variable n_jobs "Trabajos"
label variable wage "Salarios (R$ 2018)"
label variable n_jobs_np "Empleos sin fines de lucro"
label variable wage_np "Salarios sin fines de lucro (R$ 2018)"
label variable n_jobs_priv "Trabajos privados"
label variable wage_priv "Salarios privados (R$ 2018)"
label variable n_jobs_pub_fed_exec "Empleos Públicos Ejecutivos Federales"
label variable wage_pub_fed_exec "Salarios Públicos del Ejecutivo Federal (R$ 2018)"
label variable n_jobs_pub_fed_jud "Empleos Públicos Judiciales Federales"
label variable wage_pub_fed_jud "Salarios Públicos del Poder Judicial Federal (R$ 2018)"
label variable n_jobs_pub_fed_leg "Empleos Públicos Legislativos Federales"
label variable wage_pub_fed_leg "Salarios Públicos Legislativos Federales (R$ 2018)"
label variable n_jobs_pub_mun_exec "Empleos Públicos Ejecutivos Municipales"
label variable wage_pub_mun_exec "Salarios Públicos Ejecutivos Municipales (R$ 2018)"
label variable n_jobs_pub_mun_jud "Empleos Públicos Judiciales Municipales"
label variable wage_pub_mun_jud "Salarios Públicos del Poder Judicial Municipal (R$ 2018)"
label variable n_jobs_pub_mun_leg "Empleos Públicos Legislativos Municipales"
label variable wage_pub_mun_leg "Salarios Públicos Legislativos Municipales (R$ 2018)"
label variable n_jobs_pub_stt_exec "Empleos Públicos Ejecutivos Estatales"
label variable wage_pub_stt_exec "Salarios Públicos del Ejecutivo Estatal (R$ 2018)"
label variable n_jobs_pub_stt_jud "Empleos Públicos Judiciales Estatales"
label variable wage_pub_stt_jud "Salarios Públicos del Poder Judicial del Estado (R$ 2018)"
label variable n_jobs_pub_stt_leg "Empleos públicos legislativos estatales"
label variable wage_pub_stt_leg "Salarios Públicos Legislativos Estatales (R$ 2018)"
label variable n_jobs_agric "Empleos: Agricultura"
label variable n_jobs_OMM "Empleos: Petróleo, Minería y Metales"
label variable n_jobs_manuf "Empleos: Fabricación"
label variable n_jobs_constr "Empleos: Construcción"
label variable n_jobs_retail "Empleos: Venta al por menor"
label variable n_jobs_other_serv "Empleos: Otros Servicios"
label variable n_jobs_gov "Empleos: Gobierno"
label variable n_jobs_IO "Empleos: Información y Comunicación"
label variable n_jobs_missing "Empleos: Desaparecidos"
label variable wage_avg "(suma) salario_promedio"
label variable wage_dec "(suma) salario_dec"
label variable wage_total "(suma) salario_total"
label variable wage_avg_def "(suma) salario_avg_def"
label variable wage_dec_def "(suma) salario_dec_def"
label variable wage_agric "Salarios (R$ 2018): Agricultura"
label variable wage_OMM "Salarios (R$ 2018): Petróleo, Minería y Metales"
label variable wage_manuf "Salarios (R$ 2018): Industria manufacturera"
label variable wage_constr "Salarios (R$ 2018): Construcción"
label variable wage_retail "Salarios (R$ 2018): Comercio minorista"
label variable wage_other_serv "Salarios (R$ 2018): Otros Servicios"
label variable wage_gov "Salarios (R$ 2018): Gobierno"
label variable wage_IO "Salarios (R$ 2018): Información y Comunicación"
label variable wage_missing "Salarios (R$ 2018): faltantes"
label variable n_jobs_np_educ "Empleos educativos sin fines de lucro"
label variable n_jobs_priv_educ "Empleos de educación privada"
label variable n_jobs_pub_fed_exec_educ "Empleos de Educación Pública Ejecutiva Federal"
label variable n_jobs_pub_fed_jud_educ "Empleos en Educación Pública Judicial Federal"
label variable n_jobs_pub_fed_leg_educ "Empleos de educación pública legislativa federal"
label variable n_jobs_pub_mun_exec_educ "Empleos de Ejecutivo Municipal De Educación Pública"
label variable n_jobs_pub_mun_jud_educ "Empleos de Educación Pública Judicial Municipal"
label variable n_jobs_pub_mun_leg_educ "Empleos de Educación Pública Legislativa Municipal"
label variable n_jobs_pub_stt_exec_educ "Empleos de Educación Pública Ejecutiva Estatal"
label variable n_jobs_pub_stt_jud_educ "Empleos de educación pública judicial estatal"
label variable n_jobs_pub_stt_leg_educ "Empleos de educación pública legislativa estatal"
label variable wage_np_educ "Salarios de educación sin fines de lucro (R$ 2018)"
label variable wage_priv_educ "Salarios de la educación privada (R$ 2018)"
label variable wage_pub_fed_exec_educ "Salarios del Ejecutivo Federal de Educación Pública (R$ 2018)"
label variable wage_pub_fed_jud_educ "Salarios de la Educación Pública del Poder Judicial Federal (R$ 2018)"
label variable wage_pub_fed_leg_educ "Salarios de la Educación Pública Legislativa Federal (R$ 2018)"
label variable wage_pub_mun_exec_educ "Salarios del Ejecutivo Municipal de Educación Pública (R$ 2018)"
label variable wage_pub_mun_jud_educ "Salarios de Educación Pública del Poder Judicial Municipal (R$ 2018)"
label variable wage_pub_mun_leg_educ "Salarios de Educación Pública Legislativa Municipal (R$ 2018)"
label variable wage_pub_stt_exec_educ "Salarios del Ejecutivo Estatal de Educación Pública (R$ 2018)"
label variable wage_pub_stt_jud_educ "Salarios de la Educación Pública del Poder Judicial del Estado (R$ 2018)"
label variable wage_pub_stt_leg_educ "Salarios de la Educación Pública Legislativa Estatal (R$ 2018)"
label variable n_jobs_np_health "Empleos de salud sin fines de lucro"
label variable n_jobs_priv_health "Trabajos de salud privados"
label variable n_jobs_pub_fed_exec_health "Empleos de Ejecutivo Federal de Salud Pública"
label variable n_jobs_pub_fed_jud_health "Empleos en Salud Pública Judicial Federal"
label variable n_jobs_pub_fed_leg_health "Trabajos de salud pública legislativa federal"
label variable n_jobs_pub_mun_exec_health "Empleos de Ejecutivo Municipal De Salud Publica"
label variable n_jobs_pub_mun_jud_health "Empleos de Salud Pública Judicial Municipal"
label variable n_jobs_pub_mun_leg_health "Empleos de Legislativo Municipal de Salud Pública"
label variable n_jobs_pub_stt_exec_health "Empleos de ejecutivo estatal de salud pública"
label variable n_jobs_pub_stt_jud_health "Empleos de Salud Pública Judicial Estatal"
label variable n_jobs_pub_stt_leg_health "Empleos de salud pública legislativa estatal"
label variable wage_np_health "Salarios de Salud sin fines de lucro (R$ 2018)"
label variable wage_priv_health "Salarios de salud privada (R$ 2018)"
label variable wage_pub_fed_exec_health "Salarios del Ejecutivo Federal en Salud Pública (R$ 2018)"
label variable wage_pub_fed_jud_health "Salarios de Salud Pública del Poder Judicial Federal (R$ 2018)"
label variable wage_pub_fed_leg_health "Salarios Legislativos Federales de Salud Pública (R$ 2018)"
label variable wage_pub_mun_exec_health "Salarios del Ejecutivo Municipal de Salud Pública (R$ 2018)"
label variable wage_pub_mun_jud_health "Salarios de Salud Pública del Poder Judicial Municipal (R$ 2018)"
label variable wage_pub_mun_leg_health "Salarios Legislativos Municipales de Salud Pública (R$ 2018)"
label variable wage_pub_stt_exec_health "Salarios del Ejecutivo Estatal de Salud Pública (R$ 2018)"
label variable wage_pub_stt_jud_health "Salarios de Salud Pública del Poder Judicial del Estado (R$ 2018)"
label variable wage_pub_stt_leg_health "Salarios Legislativos Estatales de Salud Pública (R$ 2018)"
label variable n_estab "Establecimientos"
label variable n_estab_agric "Establecimientos: Agricultura"
label variable n_estab_OMM "Establecimientos: Petróleo, Minería y Metales"
label variable n_estab_manuf "Establecimientos: Manufactura"
label variable n_estab_constr "Establecimientos: Construcción"
label variable n_estab_retail "Establecimientos: Comercio minorista"
label variable n_estab_other_serv "Establecimientos: Otros Servicios"
label variable n_estab_gov "Establecimientos: Gobierno"
label variable n_estab_IO "Establecimientos: Información y Comunicación"
label variable n_estab_missing "Establecimientos: Desaparecidos"
