* Translated Variable Labels for RAIS_workers_BL_BL_history_sample5.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "पीआईएस/पीएएसईपी रजिस्ट्री में कर्मचारी पंजीकरण संख्या"
label variable id_estab "प्रतिष्ठान का सीएनपीजे या सीईआई (अग्रणी शून्य के बिना)"
label variable id_munic_6 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable year "वर्ष"
label variable type_contract "करार का प्रकार"
label variable type_admission "प्रवेश प्रकार"
label variable hours "काम पर रखे गए घंटे"
label variable type_wage "वेतन प्रकार"
label variable hired_wage "वेतन पर काम पर रखा गया"
label variable last_wage "अंतिम वेतन"
label variable employed_3112 "31 दिसंबर को कार्यरत"
label variable ym_admission "वर्ष-माह प्रवेश"
label variable year_admission "प्रवेश वर्ष"
label variable month_admission "प्रवेश माह"
label variable ym_separation "वर्ष-महीने का पृथक्करण"
label variable month_separation "पृथक्करण मास"
label variable cause_separation "अलगाव का कारण"
label variable time_emp "टीम नियोजित"
label variable hired "वर्ष के दौरान नियुक्त किया गया"
label variable laid_off "वर्ष के दौरान नौकरी से निकाल दिया गया"
label variable n_months "काम किये गये महीनों की संख्या"
label variable wage_avg "मासिक वेतन (R$)"
label variable wage_dec "दिसंबर वेतन (R$)"
label variable wage_total "कुल वार्षिक वेतन (R$)"
label variable wage_avg_def "मासिक वेतन (R$ 2017)"
label variable wage_dec_def "दिसंबर वेतन (R$ 2017)"
label variable wage_total_def "कुल वार्षिक वेतन (R$ 2017)"
label variable job_public "सार्वजनिक नौकरी"
label variable job_public_com "कमीशन प्राप्त सार्वजनिक नौकरी"
label variable CBO1994 "सीबीओ (व्यवसायों का ब्राजीलियाई वर्गीकरण), 1994 में बनाया गया"
label variable CBO2002 "सीबीओ (व्यवसायों का ब्राज़ीलियाई वर्गीकरण), 2002 में बनाया गया (6 अंक)"
label variable occup_cat "व्यवसाय श्रेणी (CBO2002)"
label variable education "शिक्षा का स्तर"
label variable gender "लिंग"
label variable age "आयु"
label variable nationality "राष्ट्रीयता"
label variable race "दौड़"
label variable has_disability "विकलांगता है"
label variable disability "विकलांगता"
