* Translated Variable Labels for RAIS_1992-2017_estab_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "प्रतिष्ठान का सीएनपीजे या सीईआई (अग्रणी शून्य के बिना)"
label variable id_firm "प्रतिष्ठान के सीएनपीजे का रेडिकल (8 स्थान, बाईं ओर शून्य के बिना)"
label variable id_munic_6 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable year "वर्ष"
label variable size_estab "स्थापना का आकार"
label variable type_estab "स्थापना प्रकार"
label variable legal_nature "शीतल प्रकृति"
label variable cnae1 "सीएनएई 1.0"
label variable sector1 "आर्थिक क्षेत्र 1.0 (आईबीजीई)"
label variable sector "क्षेत्र"
label variable public "जनता"
label variable public_federal "सार्वजनिक संघीय"
label variable public_state "सार्वजनिक राज्य"
label variable public_municipal "सार्वजनिक नगरपालिका"
label variable public_exec "सार्वजनिक कार्यकारी"
label variable public_leg "सार्वजनिक विधान"
label variable public_jud "सार्वजनिक न्यायपालिका"
label variable company "कंपनी"
label variable company_public "सार्वजनिक संगठन"
label variable nonprofit "गैर लाभ"
label variable cnae2 "सीएनएई 2.0"
label variable sector2 "आर्थिक क्षेत्र 2.0 (आईबीजीई)"
