* Translated Variable Labels for data_TSE_RAIS_sample5_1992-2017_worker.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "पीआईएस/पीएएसईपी रजिस्ट्री में कर्मचारी पंजीकरण संख्या"
label variable id_worker_CPF "कार्यकर्ता का सी.पी.एफ"
label variable id_estab "प्रतिष्ठान का सीएनपीजे या सीईआई (अग्रणी शून्य के बिना)"
label variable id_munic_6 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable year ""
label variable empem3112 "12/31 पर सक्रिय लिंक संकेतक (1 - हाँ; 0 - नहीं)"
label variable tpvinculo "रोजगार संबंध का प्रकार"
label variable causadesli "शटडाउन का कारण"
label variable mesdesli "कर्मचारी समाप्ति का महीना"
label variable ocupacao94 "सीबीओ (व्यवसायों का ब्राजीलियाई वर्गीकरण), 1994 में बनाया गया"
label variable mesadmissao "कर्मचारी के किराये का महीना"
label variable remdezembro "दिसंबर में श्रमिकों का पारिश्रमिक, न्यूनतम मजदूरी में"
label variable remmedia "न्यूनतम वेतन में वर्ष का औसत वेतन"
label variable tempempr "कर्मचारी के रोजगार की अवधि महीनों में (जब संचित होती है, तो योग का प्रतिनिधित्व करती है"
label variable job_public "सार्वजनिक नौकरी"
label variable job_public_com "कमीशन प्राप्त सार्वजनिक नौकरी"
label variable horascontr "प्रति सप्ताह संविदात्मक घंटों की संख्या"
label variable tipoadm "प्रवेश का प्रकार"
label variable remdezr "दिसंबर में औसत कर्मचारी पारिश्रमिक, नाममात्र मूल्य में"
label variable remmedr "नाममात्र मूल्य में वर्ष का औसत वेतन"
label variable dtadmissao "कर्मचारी के प्रवेश की तिथि (पूर्ण)"
label variable tiposal "अनुबंध वेतन का प्रकार"
label variable salcontr "कर्मचारी का संविदात्मक वेतन, नाममात्र मूल्य में"
label variable ultrem ""
label variable id_politician "आईडी राजनेता"
label variable ran_1996 "1996 तक चला"
label variable ran_1998 "1998 में चला"
label variable ran_2000 "2000 तक दौड़ा"
label variable ran_2002 "2002 चला"
label variable ran_2004 "2004 चला"
label variable ran_2006 "2006 चला"
label variable ran_2008 "2008 में चला"
label variable ran_2010 "2010 चला"
label variable ran_2012 "2012 चला"
label variable ran_2014 "2014 चला"
label variable ran_2016 "2016 चला"
label variable ran_2018 "2018 चला"
label variable office_1996 "कार्यालय 1996"
label variable office_1998 "ऑफिस 1998"
label variable office_2000 "ऑफिस 2000"
label variable office_2002 "कार्यालय 2002"
label variable office_2004 "कार्यालय 2004"
label variable office_2006 "कार्यालय 2006"
label variable office_2008 "कार्यालय 2008"
label variable office_2010 "कार्यालय 2010"
label variable office_2012 "कार्यालय 2012"
label variable office_2014 "कार्यालय 2014"
label variable office_2016 "कार्यालय 2016"
label variable office_2018 "ऑफिस 2018"
label variable elected_1996 "1996 में निर्वाचित"
label variable elected_1998 "1998 में निर्वाचित"
label variable elected_2000 "2000 में निर्वाचित"
label variable elected_2002 "2002 में चुना गया"
label variable elected_2004 "2004 में निर्वाचित"
label variable elected_2006 "2006 में चुना गया"
label variable elected_2008 "2008 में चुना गया"
label variable elected_2010 "2010 में चुना गया"
label variable elected_2012 "2012 में चुना गया"
label variable elected_2014 "2014 में चुना गया"
label variable elected_2016 "2016 में चुना गया"
label variable elected_2018 "2018 को चुना गया"
