* Translated Variable Labels for RAIS_estab_in_split_AMC_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "机构的 CNPJ 或 CEI（无前导零）"
label variable year "年"
label variable id_munic_6_m1 "机构所在地的直辖市"
label variable id_AMC_m1 "AMC ID 1991-2010"
label variable state_abbrev_m1 "州缩写"
label variable id_state_m1 "ID - 状态"
label variable n_new "分割申请人数"
label variable n_old "分割其他数量"
label variable n_almost_new "几乎分裂的申请人数量"
label variable n_almost_old "几乎分裂其他人的数量"
label variable split "分裂"
label variable almost_split "几乎分裂"
label variable year_split "第一年分裂"
label variable year_almost_split "第一年几乎分裂"
label variable split1993 ""
label variable split1997 ""
label variable split2001 ""
label variable split2005 ""
label variable split2009 ""
label variable n_splits "分割数"
label variable in_sample "样品中"
label variable in_sample_97 "样品中"
label variable almost_split_states "数据几乎分裂的州"
label variable id_munic_6 "机构所在地的直辖市"
label variable n_workers "工人人数（总计）"
label variable hired "雇用人数"
label variable laid_off "裁员人数"
label variable churn "搅动"
label variable wage_total "年工资总额（雷亚尔）"
label variable wage_avg "月工资（雷亚尔）"
label variable wage_pw "每名工人的工资（雷亚尔）"
label variable wage_total_def "年工资总额（2018 年雷亚尔）"
label variable wage_avg_def "月工资（2018 年雷亚尔）"
label variable wage_def_pw "每位工人的工资（2018 年雷亚尔）"
label variable diff_munic "不同的直辖市"
label variable incumbent_new_munic "任职于新市镇"
label variable post "邮政"
label variable tau "牛头蛋白"
label variable active "积极的"
