* Translated Variable Labels for RAIS_1995-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "机构所在地的直辖市"
label variable year "年"
label variable n_jobs "工作"
label variable wage "工资（2018 年雷亚尔）"
label variable n_jobs_np "非营利性工作"
label variable wage_np "非营利组织工资（2018 年雷亚尔）"
label variable n_jobs_priv "私人工作"
label variable wage_priv "私人工资（2018 年雷亚尔）"
label variable n_jobs_pub_fed_exec "联邦行政公共职位"
label variable wage_pub_fed_exec "联邦行政人员公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_fed_jud "联邦司法公共职位"
label variable wage_pub_fed_jud "联邦司法机构公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_fed_leg "联邦立法公共职位"
label variable wage_pub_fed_leg "联邦立法公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_mun_exec "市政行政人员公共职位"
label variable wage_pub_mun_exec "市政行政人员公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_mun_jud "市司法公共职位"
label variable wage_pub_mun_jud "市司法机构公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_mun_leg "市立法公共职位"
label variable wage_pub_mun_leg "市立法公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_stt_exec "国家行政公共职位"
label variable wage_pub_stt_exec "国家行政人员公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_stt_jud "国家司法公共职位"
label variable wage_pub_stt_jud "州司法机构公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_stt_leg "州立法公共职位"
label variable wage_pub_stt_leg "州立法公共工资（2018 年雷亚尔）"
label variable n_jobs_np_educ "非营利教育工作"
label variable n_jobs_priv_educ "私立教育工作"
label variable n_jobs_pub_fed_exec_educ "联邦行政公共教育职位"
label variable n_jobs_pub_fed_jud_educ "联邦司法公共教育职位"
label variable n_jobs_pub_fed_leg_educ "联邦立法公共教育职位"
label variable n_jobs_pub_mun_exec_educ "市行政公共教育职位"
label variable n_jobs_pub_mun_jud_educ "市司法公共教育岗位"
label variable n_jobs_pub_mun_leg_educ "市立法公共教育职位"
label variable n_jobs_pub_stt_exec_educ "国家行政公共教育职位"
label variable n_jobs_pub_stt_jud_educ "国家司法公共教育职位"
label variable n_jobs_pub_stt_leg_educ "州立法公共教育职位"
label variable wage_np_educ "非营利教育工资（2018 年雷亚尔）"
label variable wage_priv_educ "私立教育工资（2018 年雷亚尔）"
label variable wage_pub_fed_exec_educ "联邦行政公共教育工资（2018 年雷亚尔）"
label variable wage_pub_fed_jud_educ "联邦司法机构公共教育工资（2018 年雷亚尔）"
label variable wage_pub_fed_leg_educ "联邦立法公共教育工资（2018 年雷亚尔）"
label variable wage_pub_mun_exec_educ "市行政人员公共教育工资（2018 年雷亚尔）"
label variable wage_pub_mun_jud_educ "市司法机关公共教育工资（2018 年雷亚尔）"
label variable wage_pub_mun_leg_educ "市立法公共教育工资（2018 年雷亚尔）"
label variable wage_pub_stt_exec_educ "国家行政人员公共教育工资（2018 年雷亚尔）"
label variable wage_pub_stt_jud_educ "州司法机构公共教育工资（2018 年雷亚尔）"
label variable wage_pub_stt_leg_educ "州立法公共教育工资（2018 年雷亚尔）"
label variable n_jobs_np_health "非营利健康工作"
label variable n_jobs_priv_health "私人健康工作"
label variable n_jobs_pub_fed_exec_health "联邦行政公共卫生职位"
label variable n_jobs_pub_fed_jud_health "联邦司法公共卫生职位"
label variable n_jobs_pub_fed_leg_health "联邦立法公共卫生职位"
label variable n_jobs_pub_mun_exec_health "市政行政公共卫生职位"
label variable n_jobs_pub_mun_jud_health "市司法公共卫生职位"
label variable n_jobs_pub_mun_leg_health "市立法公共卫生职位"
label variable n_jobs_pub_stt_exec_health "国家行政公共卫生职位"
label variable n_jobs_pub_stt_jud_health "国家司法公共卫生职位"
label variable n_jobs_pub_stt_leg_health "州立法公共卫生职位"
label variable wage_np_health "非营利健康工资（2018 年雷亚尔）"
label variable wage_priv_health "私人医疗保健工资（2018 年雷亚尔）"
label variable wage_pub_fed_exec_health "联邦行政人员公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_fed_jud_health "联邦司法机构公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_fed_leg_health "联邦立法公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_mun_exec_health "市行政人员公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_mun_jud_health "市司法机构公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_mun_leg_health "市立法公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_stt_exec_health "国家行政人员公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_stt_jud_health "州司法机构公共卫生工资（2018 年雷亚尔）"
label variable wage_pub_stt_leg_health "州立法公共卫生工资（2018 年雷亚尔）"
label variable n_estab "机构"
label variable n_estab_ag "机构：农业"
label variable n_estab_extr "机构：采掘业"
label variable n_estab_transf "机构：转型行业"
label variable n_estab_EGW "设施：电力、燃气和水"
label variable n_estab_constr "机构：建筑业"
label variable n_estab_comm "机构：通讯"
label variable n_estab_TSC "设施：运输、仓储、通讯"
label variable n_estab_LF "设施：住宿和餐饮"
label variable n_estab_IC "机构：信息和通讯"
label variable n_estab_fin "机构：财务"
label variable n_estab_real_estate "机构：房地产"
label variable n_estab_CST "机构：文职、科学或技术机构"
label variable n_estab_admin "机构设置：行政"
label variable n_estab_PADSS "机构：公共管理、国防或社会服务"
label variable n_estab_educ "机构：教育"
label variable n_estab_HSS "机构：健康或社会服务"
label variable n_estab_ACS "机构：艺术、文化和体育"
label variable n_estab_OS "机构：其他服务"
label variable n_estab_DS "机构：家庭服务"
label variable n_estab_IO "机构：国际组织"
label variable n_estab_fishing "场所：钓鱼"
label variable n_estab_OSS "机构：其他社会服务"
label variable n_estab_missing "机构：缺失"
