* Translated Variable Labels for RAIS_1985-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "机构所在地的直辖市"
label variable year "年"
label variable n_jobs "工作"
label variable n_educ_workers "教育工作者人数"
label variable n_health_workers "卫生工作者人数"
label variable n_estab "机构"
label variable wage_total_def "工资（2018 年雷亚尔）"
label variable n_jobs_np "非营利性工作"
label variable wage_total_def_np "非营利性工资（2018 年雷亚尔）"
label variable n_jobs_priv "私人工作"
label variable wage_total_def_priv "私人工资（2018 年雷亚尔）"
label variable n_jobs_pub_fed_exec "联邦行政公共职位"
label variable wage_total_def_pub_fed_exec "联邦行政人员公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_fed_jud "联邦司法公共职位"
label variable wage_total_def_pub_fed_jud "联邦司法机构公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_fed_leg "联邦立法公共职位"
label variable wage_total_def_pub_fed_leg "联邦立法公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_mun_exec "市政行政人员公共职位"
label variable wage_total_def_pub_mun_exec "市政行政人员公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_mun_jud "市司法公共职位"
label variable wage_total_def_pub_mun_jud "市司法机关公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_mun_leg "市立法公共职位"
label variable wage_total_def_pub_mun_leg "市立法公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_stt_exec "国家行政公共职位"
label variable wage_total_def_pub_stt_exec "国家行政人员公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_stt_jud "国家司法公共职位"
label variable wage_total_def_pub_stt_jud "州司法机构公共工资（2018 年雷亚尔）"
label variable n_jobs_pub_stt_leg "州立法公共职位"
label variable wage_total_def_pub_stt_leg "州立法公共工资（2018 年雷亚尔）"
