* Translated Variable Labels for data_judges_characteristics.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "法官"
label variable gender "性别"
label variable race "种族"
label variable birth_year "出生年"
label variable education ""
label variable educ_basic "直至基本"
label variable educ_hs "中学"
label variable educ_college "大学"
label variable educ_grad "研究所"
label variable first_year_RAIS "RAIS 第一年"
label variable first_year_RAIS_public "公共工作第一年"
label variable first_year_RAIS_jud "司法工作第一年"
label variable first_wage_RAIS "RAIS 中的第一笔工资（2017 年雷亚尔）"
label variable prior_wage_bef_public "担任公职之前的工资（2017 年雷亚尔）"
label variable prior_wage_bef_jud "司法部门工作之前的工资（2017 年雷亚尔）"
label variable avg_wage_bef_public "公职前平均工资（2017 年雷亚尔）"
label variable avg_wage_bef_jud "司法部门工作前的平均工资（2017 年雷亚尔）"
label variable first_munic_RAIS "RAIS 中的第一个市镇"
label variable first_munic_public "第一个公共工作城市"
label variable first_munic_jud "第一直辖市司法工作"
