* Translated Variable Labels for RAIS_1995-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable year "वर्ष"
label variable n_jobs "नौकरियां"
label variable wage "मजदूरी (R$ 2018)"
label variable n_jobs_np "गैर-लाभकारी नौकरियाँ"
label variable wage_np "गैर-लाभकारी मजदूरी (R$ 2018)"
label variable n_jobs_priv "निजी नौकरियाँ"
label variable wage_priv "निजी मज़दूरी (R$ 2018)"
label variable n_jobs_pub_fed_exec "संघीय कार्यकारी सार्वजनिक नौकरियाँ"
label variable wage_pub_fed_exec "संघीय कार्यकारी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_fed_jud "संघीय न्यायिक सार्वजनिक नौकरियाँ"
label variable wage_pub_fed_jud "संघीय न्यायपालिका सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_fed_leg "संघीय विधायी सार्वजनिक नौकरियाँ"
label variable wage_pub_fed_leg "संघीय विधायी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_mun_exec "नगर निगम कार्यकारी सार्वजनिक नौकरियाँ"
label variable wage_pub_mun_exec "नगरपालिका कार्यकारी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_mun_jud "नगर न्यायिक सार्वजनिक नौकरियाँ"
label variable wage_pub_mun_jud "नगरपालिका न्यायपालिका सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_mun_leg "नगरपालिका विधायी सार्वजनिक नौकरियाँ"
label variable wage_pub_mun_leg "नगरपालिका विधायी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_stt_exec "राज्य कार्यकारी सार्वजनिक नौकरियाँ"
label variable wage_pub_stt_exec "राज्य कार्यकारी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_stt_jud "राज्य न्यायिक सार्वजनिक नौकरियाँ"
label variable wage_pub_stt_jud "राज्य न्यायपालिका सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_stt_leg "राज्य विधायी सार्वजनिक नौकरियाँ"
label variable wage_pub_stt_leg "राज्य विधायी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_np_educ "गैर-लाभकारी शिक्षा नौकरियाँ"
label variable n_jobs_priv_educ "निजी शिक्षा नौकरियाँ"
label variable n_jobs_pub_fed_exec_educ "संघीय कार्यकारी सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_fed_jud_educ "संघीय न्यायिक सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_fed_leg_educ "संघीय विधायी सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_mun_exec_educ "नगर निगम कार्यकारी सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_mun_jud_educ "नगर न्यायिक सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_mun_leg_educ "नगर विधायी सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_stt_exec_educ "राज्य कार्यकारी सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_stt_jud_educ "राज्य न्यायिक सार्वजनिक शिक्षा नौकरियाँ"
label variable n_jobs_pub_stt_leg_educ "राज्य विधान लोक शिक्षा नौकरियाँ"
label variable wage_np_educ "गैर-लाभकारी शिक्षा वेतन (R$ 2018)"
label variable wage_priv_educ "निजी शिक्षा वेतन (R$ 2018)"
label variable wage_pub_fed_exec_educ "संघीय कार्यकारी सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_fed_jud_educ "संघीय न्यायपालिका सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_fed_leg_educ "संघीय विधायी सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_mun_exec_educ "नगरपालिका कार्यकारी सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_mun_jud_educ "नगरपालिका न्यायपालिका सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_mun_leg_educ "नगरपालिका विधान लोक शिक्षा वेतन (आर$ 2018)"
label variable wage_pub_stt_exec_educ "राज्य कार्यकारी सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_stt_jud_educ "राज्य न्यायपालिका सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable wage_pub_stt_leg_educ "राज्य विधायी सार्वजनिक शिक्षा वेतन (R$ 2018)"
label variable n_jobs_np_health "गैर-लाभकारी स्वास्थ्य नौकरियाँ"
label variable n_jobs_priv_health "निजी स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_fed_exec_health "संघीय कार्यकारी सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_fed_jud_health "संघीय न्यायिक सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_fed_leg_health "संघीय विधायी सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_mun_exec_health "नगर निगम कार्यकारी सार्वजनिक स्वास्थ्य नौकरियां"
label variable n_jobs_pub_mun_jud_health "नगर न्यायिक सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_mun_leg_health "नगर विधायी सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_stt_exec_health "राज्य कार्यकारी सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_stt_jud_health "राज्य न्यायिक सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable n_jobs_pub_stt_leg_health "राज्य विधायी सार्वजनिक स्वास्थ्य नौकरियाँ"
label variable wage_np_health "गैर-लाभकारी स्वास्थ्य मजदूरी (R$ 2018)"
label variable wage_priv_health "निजी स्वास्थ्य मजदूरी (R$ 2018)"
label variable wage_pub_fed_exec_health "संघीय कार्यकारी सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_fed_jud_health "संघीय न्यायपालिका सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_fed_leg_health "संघीय विधायी सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_mun_exec_health "नगरपालिका कार्यकारी सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_mun_jud_health "नगरपालिका न्यायपालिका सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_mun_leg_health "नगरपालिका विधायी सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_stt_exec_health "राज्य कार्यकारी सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_stt_jud_health "राज्य न्यायपालिका सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable wage_pub_stt_leg_health "राज्य विधायी सार्वजनिक स्वास्थ्य वेतन (R$ 2018)"
label variable n_estab "प्रतिष्ठानों"
label variable n_estab_ag "प्रतिष्ठान: कृषि"
label variable n_estab_extr "प्रतिष्ठान: निष्कर्षण उद्योग"
label variable n_estab_transf "प्रतिष्ठान: परिवर्तन उद्योग"
label variable n_estab_EGW "प्रतिष्ठान: बिजली, गैस और पानी"
label variable n_estab_constr "प्रतिष्ठान: निर्माण"
label variable n_estab_comm "प्रतिष्ठान: संचार"
label variable n_estab_TSC "प्रतिष्ठान: परिवहन, भंडारण और संचार"
label variable n_estab_LF "प्रतिष्ठान: आवास एवं भोजन"
label variable n_estab_IC "प्रतिष्ठान: सूचना एवं संचार"
label variable n_estab_fin "प्रतिष्ठान: वित्त"
label variable n_estab_real_estate "प्रतिष्ठान: रियल एस्टेट"
label variable n_estab_CST "प्रतिष्ठान: लिपिकीय, विज्ञान या तकनीकी"
label variable n_estab_admin "प्रतिष्ठान: प्रशासनिक"
label variable n_estab_PADSS "प्रतिष्ठान: लोक प्रशासन, रक्षा या सामाजिक सेवाएँ"
label variable n_estab_educ "प्रतिष्ठान: शिक्षा"
label variable n_estab_HSS "प्रतिष्ठान: स्वास्थ्य या सामाजिक सेवाएँ"
label variable n_estab_ACS "प्रतिष्ठान: कला, संस्कृति और खेल"
label variable n_estab_OS "प्रतिष्ठान: अन्य सेवाएँ"
label variable n_estab_DS "प्रतिष्ठान: घरेलू सेवाएँ"
label variable n_estab_IO "प्रतिष्ठान: अंतर्राष्ट्रीय संगठन"
label variable n_estab_fishing "प्रतिष्ठान: मछली पकड़ना"
label variable n_estab_OSS "प्रतिष्ठान: अन्य सामाजिक सेवाएँ"
label variable n_estab_missing "प्रतिष्ठानः गायब"
