* Translated Variable Labels for RAIS_1985-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable year "वर्ष"
label variable n_jobs "नौकरियां"
label variable n_educ_workers "शिक्षाकर्मियों की संख्या"
label variable n_health_workers "स्वास्थ्य कर्मियों की संख्या"
label variable n_estab "प्रतिष्ठानों"
label variable wage_total_def "मजदूरी (R$ 2018)"
label variable n_jobs_np "गैर-लाभकारी नौकरियाँ"
label variable wage_total_def_np "गैर-लाभकारी मजदूरी (R$ 2018)"
label variable n_jobs_priv "निजी नौकरियाँ"
label variable wage_total_def_priv "निजी मज़दूरी (R$ 2018)"
label variable n_jobs_pub_fed_exec "संघीय कार्यकारी सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_fed_exec "संघीय कार्यकारी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_fed_jud "संघीय न्यायिक सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_fed_jud "संघीय न्यायपालिका सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_fed_leg "संघीय विधायी सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_fed_leg "संघीय विधायी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_mun_exec "नगर निगम कार्यकारी सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_mun_exec "नगरपालिका कार्यकारी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_mun_jud "नगर न्यायिक सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_mun_jud "नगरपालिका न्यायपालिका सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_mun_leg "नगरपालिका विधायी सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_mun_leg "नगरपालिका विधायी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_stt_exec "राज्य कार्यकारी सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_stt_exec "राज्य कार्यकारी सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_stt_jud "राज्य न्यायिक सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_stt_jud "राज्य न्यायपालिका सार्वजनिक वेतन (R$ 2018)"
label variable n_jobs_pub_stt_leg "राज्य विधायी सार्वजनिक नौकरियाँ"
label variable wage_total_def_pub_stt_leg "राज्य विधायी सार्वजनिक वेतन (R$ 2018)"
