* Translated Variable Labels for data_judges_15_20_characteristics.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "ID - Juge (Interne)"
label variable gender "Genre"
label variable race "Course"
label variable birth_year "Année de naissance"
label variable educ_basic "Jusqu'au niveau de base"
label variable educ_hs "lycée"
label variable educ_college "Collège"
label variable educ_grad "Lycée"
label variable first_year_RAIS "Première année en RAIS"
label variable first_year_RAIS_public "Première année dans un emploi public"
label variable first_year_RAIS_jud "Première année dans le secteur judiciaire"
label variable first_wage_RAIS "Premier salaire en RAIS (R$ 2017)"
label variable prior_wage_bef_public "Salaire avant emploi public (R$ 2017)"
label variable prior_wage_bef_jud "Salaire avant l'emploi dans la magistrature (R$ 2017)"
label variable avg_wage_bef_public "Salaire moyen avant emploi public (R$ 2017)"
label variable avg_wage_bef_jud "Salaire moyen avant emploi judiciaire (R$ 2017)"
label variable first_munic_RAIS "Première municipalité du RAIS"
label variable first_munic_public "Première municipalité en emploi public"
label variable first_munic_jud "Première municipalité dans le domaine judiciaire"
