* Translated Variable Labels for data_judges_employment_history_deidentified.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "juge"
label variable name "juge"
label variable state_1_worked_from_CNJ ""
label variable state_2_worked_from_CNJ ""
label variable state_3_worked_from_CNJ ""
label variable id_worker_CTPS "Agent d'identification - CTPS"
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year "Année"
label variable CBO1994 "CBO (Classification Brésilienne des Professions), créée en 1994"
label variable time_emp "Équipe employée"
label variable hours "Heures embauchées"
label variable type_admission "Type d'admission"
label variable employed_3112 "En poste au 31 décembre"
label variable year_admission "Année d'admission"
label variable month_admission "Mois d'admission"
label variable month_separation "Mois de séparation"
label variable ym_admission "Admission année-mois"
label variable ym_separation "Séparation Année-Mois"
label variable hired "Embauché au cours de l'année"
label variable laid_off "Mis à pied au cours de l'année"
label variable n_months "Nombre de mois travaillés"
label variable type_contract "Type de contrat"
label variable cause_separation "Cause de séparation"
label variable wage_avg "Salaire mensuel (R$)"
label variable wage_dec "Salaire de décembre (R$)"
label variable wage_total "Salaire annuel total ($ R$)"
label variable wage_avg_def "Salaire mensuel (R$ 2017)"
label variable wage_dec_def "Salaire de décembre (R$ 2017)"
label variable wage_total_def "Salaire annuel total (R$ 2017)"
label variable job_public "Emploi public"
label variable job_public_com "Emploi public commandé"
label variable CBO2002 "OCB 2002"
label variable occup_cat "Catégorie professionnelle (CBO2002)"
label variable size_estab "Taille de l'établissement"
label variable type_estab "Type d'établissement"
label variable legal_nature "Nature fraîche"
label variable cnae1 "CNAE 1.0"
label variable sector1 "Secteur Économique 1.0 (IBGE)"
label variable sector "Secteur"
label variable public "Publique"
label variable public_federal "Public Fédéral"
label variable public_state "État public"
label variable public_municipal "Public Municipal"
label variable public_exec "Exécutif public"
label variable public_leg "Législative publique"
label variable public_jud "Pouvoir judiciaire public"
label variable company "Entreprise"
label variable company_public "Entreprise publique"
label variable nonprofit "Non lucratif"
label variable education "niveau d'éducation"
label variable gender "Genre"
label variable age "Âge"
label variable nationality "Nationalité"
label variable type_wage "Type de salaire"
label variable hired_wage "Salaire embauché"
label variable last_wage "Dernier salaire"
label variable has_disability "A un handicap"
label variable race "Course"
label variable cnae2 "CNAE 2.0"
label variable sector2 "Secteur Économique 2.0 (IBGE)"
label variable disability "Invalidité"
