* Translated Variable Labels for data_judges_employment_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "judge"
label variable name "Name"
label variable id_estab "CNPJ or CEI of the establishment (without leading zeros)"
label variable id_firm "Radical of the establishment's CNPJ (8 positions, without zeros on the left)"
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable CBO1994 "CBO (Brazilian Classification of Occupations), created in 1994"
label variable time_emp "Team Employed"
label variable hours "Hours Hired"
label variable type_admission "Admission Type"
label variable employed_3112 "Employed on December 31"
label variable year_admission "Admission Year"
label variable month_admission "Admission Month"
label variable month_separation "Separation Month"
label variable ym_admission "Year-Month Admission"
label variable ym_separation "Year-Month Separation"
label variable hired "Hired During Year"
label variable laid_off "Laid Off During Year"
label variable n_months "Number of Months Worked"
label variable type_contract "Contract Type"
label variable cause_separation "Separation Cause"
label variable wage_avg "Monthly Wage (R$)"
label variable wage_dec "December Wage (R$)"
label variable wage_total "Total Yearly Wage (R$)"
label variable wage_avg_def "Monthly Wage (R$ 2017)"
label variable wage_dec_def "December Wage (R$ 2017)"
label variable wage_total_def "Total Yearly Wage (R$ 2017)"
label variable job_public "Public Job"
label variable job_public_com "Commissioned Public Job"
label variable CBO2002 "CBO 2002"
label variable occup_cat "Occupation Category (CBO2002)"
label variable size_estab "Establishment Size"
label variable type_estab "Establishment Type"
label variable legal_nature "Cool Nature"
label variable cnae1 "CNAE 1.0"
label variable sector1 "Economic Sector 1.0 (IBGE)"
label variable sector "Sector"
label variable public "Public"
label variable public_federal "Public Federal"
label variable public_state "Public State"
label variable public_municipal "Public Municipal"
label variable public_exec "Public Executive"
label variable public_leg "Public Legislative"
label variable public_jud "Public Judiciary"
label variable company "Company"
label variable company_public "Public Company"
label variable nonprofit "Non-Profit"
label variable education "Education Level"
label variable gender "Gender"
label variable age "Age"
label variable nationality "Nationality"
label variable type_wage "Wage Type"
label variable hired_wage "Wage Hired"
label variable last_wage "Last Wage"
label variable has_disability "Has Disability"
label variable race "Race"
label variable cnae2 "CNAE 2.0"
label variable sector2 "Economic Sector 2.0 (IBGE)"
label variable disability "Disability"
