* Translated Variable Labels for data_judges_characteristics.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_judge "judge"
label variable gender "Gender"
label variable race "Race"
label variable birth_year "Birth Year"
label variable education ""
label variable educ_basic "Up to Basic"
label variable educ_hs "high school"
label variable educ_college "college"
label variable educ_grad "Graduate School"
label variable first_year_RAIS "First Year in RAIS"
label variable first_year_RAIS_public "First Year in Public Job"
label variable first_year_RAIS_jud "First Year in Judiciary Job"
label variable first_wage_RAIS "First Wage in RAIS (R$ 2017)"
label variable prior_wage_bef_public "Wage Prior to Public Job (R$ 2017)"
label variable prior_wage_bef_jud "Wage Prior to Judiciary Job (R$ 2017)"
label variable avg_wage_bef_public "Average Wage Before Public Job (R$ 2017)"
label variable avg_wage_bef_jud "Average Wage Before Judiciary Job (R$ 2017)"
label variable first_munic_RAIS "First Municipality in RAIS"
label variable first_munic_public "First Municipality in Public Job"
label variable first_munic_jud "First Municipality in Judiciary Job"
