* Translated Variable Labels for data_TSE_RAIS_sample5_1992-2017_worker.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "Numéro d’inscription du salarié au registre PIS/PASEP"
label variable id_worker_CPF "CPF du travailleur"
label variable id_estab "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year ""
label variable empem3112 "Indicateur de lien actif au 31/12 (1 - oui ; 0 - non)"
label variable tpvinculo "Type de relation de travail"
label variable causadesli "Cause de l'arrêt"
label variable mesdesli "Mois de cessation d'emploi du salarié"
label variable ocupacao94 "CBO (Classification Brésilienne des Professions), créée en 1994"
label variable mesadmissao "Mois d'embauche du travailleur"
label variable remdezembro "Rémunération des travailleurs en décembre, en salaire minimum"
label variable remmedia "Salaire moyen de l'année en SMIC"
label variable tempempr "La durée d'emploi du travailleur en mois (une fois cumulée, elle représente la somme des"
label variable job_public "Emploi public"
label variable job_public_com "Emploi public commandé"
label variable horascontr "Nombre d'heures contractuelles par semaine"
label variable tipoadm "Type d'admission"
label variable remdezr "Rémunération moyenne des travailleurs en décembre, en valeur nominale"
label variable remmedr "Salaire moyen de l'année en valeur nominale"
label variable dtadmissao "Date d'admission du travailleur (Complet)"
label variable tiposal "Type de contrat"
label variable salcontr "Le salaire contractuel du travailleur, en valeur nominale"
label variable ultrem ""
label variable id_politician "Politicien d'identité"
label variable ran_1996 "A couru en 1996"
label variable ran_1998 "A couru en 1998"
label variable ran_2000 "A couru 2000"
label variable ran_2002 "A couru en 2002"
label variable ran_2004 "A couru en 2004"
label variable ran_2006 "A couru en 2006"
label variable ran_2008 "A couru en 2008"
label variable ran_2010 "A couru en 2010"
label variable ran_2012 "A couru en 2012"
label variable ran_2014 "A couru en 2014"
label variable ran_2016 "Couru en 2016"
label variable ran_2018 "Couru en 2018"
label variable office_1996 "Bureau 1996"
label variable office_1998 "Bureau 1998"
label variable office_2000 "Bureau 2000"
label variable office_2002 "Bureau 2002"
label variable office_2004 "Bureau 2004"
label variable office_2006 "Bureau 2006"
label variable office_2008 "Bureau 2008"
label variable office_2010 "Bureau 2010"
label variable office_2012 "Bureau 2012"
label variable office_2014 "Bureau 2014"
label variable office_2016 "Bureau 2016"
label variable office_2018 "Bureau 2018"
label variable elected_1996 "Élu en 1996"
label variable elected_1998 "Élu en 1998"
label variable elected_2000 "Élu en 2000"
label variable elected_2002 "Élu en 2002"
label variable elected_2004 "Élu en 2004"
label variable elected_2006 "Élu en 2006"
label variable elected_2008 "Élu en 2008"
label variable elected_2010 "Élu en 2010"
label variable elected_2012 "Élu en 2012"
label variable elected_2014 "Élu en 2014"
label variable elected_2016 "Élu en 2016"
label variable elected_2018 "Élu en 2018"
