* Translated Variable Labels for RAIS_workers_matched_BL_history_sample5.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "Employee registration number in the PIS/PASEP Registry"
label variable id_estab "CNPJ or CEI of the establishment (without leading zeros)"
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable type_contract "Contract Type"
label variable type_admission "Admission Type"
label variable hours "Hours Hired"
label variable type_wage "Wage Type"
label variable hired_wage "Wage Hired"
label variable last_wage "Last Wage"
label variable employed_3112 "Employed on December 31"
label variable ym_admission "Year-Month Admission"
label variable year_admission "Admission Year"
label variable month_admission "Admission Month"
label variable ym_separation "Year-Month Separation"
label variable month_separation "Separation Month"
label variable cause_separation "Separation Cause"
label variable time_emp "Team Employed"
label variable hired "Hired During Year"
label variable laid_off "Laid Off During Year"
label variable n_months "Number of Months Worked"
label variable wage_avg "Monthly Wage (R$)"
label variable wage_dec "December Wage (R$)"
label variable wage_total "Total Yearly Wage (R$)"
label variable wage_avg_def "Monthly Wage (R$ 2017)"
label variable wage_dec_def "December Wage (R$ 2017)"
label variable wage_total_def "Total Yearly Wage (R$ 2017)"
label variable job_public "Public Job"
label variable job_public_com "Commissioned Public Job"
label variable CBO1994 "CBO (Brazilian Classification of Occupations), created in 1994"
label variable CBO2002 "CBO (Brazilian Classification of Occupations), created in 2002 (6 digits)"
label variable occup_cat "Occupation Category (CBO2002)"
label variable education "Education Level"
label variable gender "Gender"
label variable age "Age"
label variable nationality "Nationality"
label variable race "Race"
label variable has_disability "Has Disability"
label variable disability "Disability"
