* Translated Variable Labels for RAIS_1992-2017_estab_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ or CEI of the establishment (without leading zeros)"
label variable id_firm "Radical of the establishment's CNPJ (8 positions, without zeros on the left)"
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable size_estab "Establishment Size"
label variable type_estab "Establishment Type"
label variable legal_nature "Cool Nature"
label variable cnae1 "CNAE 1.0"
label variable sector1 "Economic Sector 1.0 (IBGE)"
label variable sector "Sector"
label variable public "Public"
label variable public_federal "Public Federal"
label variable public_state "Public State"
label variable public_municipal "Public Municipal"
label variable public_exec "Public Executive"
label variable public_leg "Public Legislative"
label variable public_jud "Public Judiciary"
label variable company "Company"
label variable company_public "Public Company"
label variable nonprofit "Non-Profit"
label variable cnae2 "CNAE 2.0"
label variable sector2 "Economic Sector 2.0 (IBGE)"
