* Translated Variable Labels for RAIS_1992-2017_estab_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "机构的 CNPJ 或 CEI（无前导零）"
label variable id_firm "建制派 CNPJ 的激进派（8 个位置，左边没有零）"
label variable id_munic_6 "机构所在地的直辖市"
label variable year "年"
label variable size_estab "机构规模"
label variable type_estab "机构类型"
label variable legal_nature "凉爽的自然"
label variable cnae1 "中国工程院1.0"
label variable sector1 "经济部门 1.0 (IBGE)"
label variable sector "部门"
label variable public "民众"
label variable public_federal "公共联邦"
label variable public_state "公共国家"
label variable public_municipal "公共市政"
label variable public_exec "公共行政人员"
label variable public_leg "公共立法"
label variable public_jud "公共司法机构"
label variable company "公司"
label variable company_public "上市公司"
label variable nonprofit "非营利组织"
label variable cnae2 "中国工程院2.0"
label variable sector2 "经济部门 2.0 (IBGE)"
