* Translated Variable Labels for RAIS_workers_matched_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_worker_PIS "PIS/PASEP 登记处的员工注册号"
label variable id_estab "机构的 CNPJ 或 CEI（无前导零）"
label variable id_munic_6 "机构所在地的直辖市"
label variable year "年"
label variable type_contract "合同类型"
label variable type_admission "入学类型"
label variable hours "雇用时间"
label variable type_wage "工资类型"
label variable hired_wage "工资聘用"
label variable last_wage "最后工资"
label variable employed_3112 "12月31日入职"
label variable ym_admission "年月入学"
label variable year_admission "入学年份"
label variable month_admission "入学月份"
label variable ym_separation "年月分离"
label variable month_separation "分离月"
label variable cause_separation "分手原因"
label variable time_emp "雇佣团队"
label variable hired "年内受聘"
label variable laid_off "年内被解雇"
label variable n_months "工作月数"
label variable wage_avg "月工资（雷亚尔）"
label variable wage_dec "12 月工资（雷亚尔）"
label variable wage_total "年工资总额（雷亚尔）"
label variable wage_avg_def "月工资（2017 年雷亚尔）"
label variable wage_dec_def "12 月工资（2017 年雷亚尔）"
label variable wage_total_def "年工资总额（2017 年雷亚尔）"
label variable job_public "公共工作"
label variable job_public_com "委托公共工作"
label variable CBO1994 "CBO（巴西职业分类），创建于 1994 年"
label variable CBO2002 "CBO（巴西职业分类），创建于 2002 年（6 位数字）"
label variable occup_cat "职业类别（CBO2002）"
label variable education "教育程度"
label variable gender "性别"
label variable age "年龄"
label variable nationality "国籍"
label variable race "种族"
label variable has_disability "有残疾"
label variable disability "失能"
