* Translated Variable Labels for RAIS_1987.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "PIS/PASEP 登记处的员工注册号"
label variable identificad "机构的 CNPJ 或 CEI（无前导零）"
label variable radiccnpj "建制派 CNPJ 的激进派（8 个位置，左边没有零）"
label variable municipio "机构所在地的直辖市"
label variable uf "联邦团结"
label variable tpvinculo "雇佣关系类型"
label variable sitvinculo "债券状况"
label variable empem3112 "12/31 上的活动链接指示器（1 - 是；0 - 否）"
label variable anoadm "入学年份"
label variable mesadmissao "雇用工人的月份"
label variable causadesli "停机原因"
label variable mesdesli "雇员解雇月份"
label variable ocupacao94 "CBO（巴西职业分类），创建于 1994 年"
label variable grinstrucao "教学程度"
label variable genero "性别"
label variable faixaetaria "年龄范围"
label variable nacionalidad "国籍"
label variable remdezembro "12月份工人薪酬，以最低工资计算"
label variable remmedia "最低工资中当年平均工资"
label variable tempempr "工人的受雇年限（以月为单位）（累计时，代表"
label variable tamestab "机构规模 - 12/31 在职员工"
label variable tipoestbl "报告机构类型（CNPJ、CEI、未识别或忽略）"
label variable ibgesubsetor "IBGE 机构分部门"
label variable ibgeatividade "IBGE 机构活动"
label variable bairrossp "SP 社区"
label variable distritossp "SP 区"
