* Translated Variable Labels for RAIS_2018.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "PIS/PASEP 登记处的员工注册号"
label variable CPF "工人的公积金"
label variable numectps "工人的 CTPS 号码"
label variable nome "工人姓名"
label variable identificad "机构的 CNPJ 或 CEI（无前导零）"
label variable radiccnpj "建制派 CNPJ 的激进派（8 个位置，左边没有零）"
label variable municipio "机构所在地的直辖市"
label variable tpvinculo "雇佣关系类型"
label variable empem3112 "12/31 上的活动链接指示器（1 - 是；0 - 否）"
label variable tipoadm "RECODE oftipoadm（准入类型）"
label variable dtadmissao "工人入境日期（完整）"
label variable causadesli "停机原因"
label variable mesdesli "雇员解雇月份"
label variable diadesli "工人解雇日"
label variable ocupacao94 "CBO（巴西职业分类），创建于 1994 年"
label variable ocup2002 "CBO（巴西职业分类），创建于 2002 年（6 位数字）"
label variable grinstrucao "教学程度"
label variable genero "性别"
label variable dtnascimento "工人的出生日期"
label variable idade "工人年龄"
label variable nacionalidad "国籍"
label variable portdefic "没有残疾"
label variable tpdefic "残疾类型"
label variable raca_cor "工人的种族和肤色"
label variable remdezembro "12月份工人薪酬，以最低工资计算"
label variable remmedia "当年最低工资平均工资"
label variable remdezr "12月份工人平均工资（名义值）"
label variable remmedr "当年平均工资名义值"
label variable tempempr "工人的工作年限（以月为单位）（累计时，代表"
label variable tiposal "合同类型 薪资"
label variable salcontr "工人的合同工资（名义值）"
label variable ultrem "工人最后收到的报酬（名义值）"
label variable horascontr "每周合同工时数"
label variable sbclas20 "经济活动组，根据 CNAE 2.0 分类"
label variable clascnae95 "CNAE 1.0 级（企业的主要活动）"
label variable clascnae20 "CNAE 2.0 级（企业的主要活动）"
label variable tamestab "机构规模 - 12/31 在职员工"
label variable natjuridica "机构的法律性质"
label variable tipoestbl "报告机构类型（CNPJ、CEI、未识别或忽略）"
label variable indceivinc "与 CEI 关联的建立指标"
label variable ceivinc "链接的 CEI 编号（如果有）"
label variable indalvara "具有司法许可的工人指标"
label variable indpat "属于 PAT 的机构指标"
label variable indsimples "SIMPLES 选择指标"
label variable qtdiasafas "离开天数"
label variable ibgesubsetor "IBGE分部门"
label variable anochegbr "抵达巴西年份"
label variable cepestab "机构邮政编码"
label variable muntrab "工人自治市"
label variable razaosocial "机构的公司名称"
label variable indtrabparc "部分工作指示器"
label variable indtrabint "间歇工作指示器"
label variable remjan "1月份工人平均工资（名义值）"
label variable remfev "2月份工人平均工资（名义值）"
label variable remmar "3月份工人平均工资（名义值）"
label variable remabr "4月份工人平均工资（名义值）"
label variable remmai "5月份工人平均工资（名义值）"
label variable remjun "6月份工人平均工资（名义值）"
label variable remjul "7月份工人平均工资（名义值）"
label variable remago "8月份工人平均工资（名义值）"
label variable remset "9月份工人平均工资（名义值）"
label variable remout "10月份工人平均工资（名义值）"
label variable remnov "11月份工人平均工资（名义值）"
label variable causafast1 "工人在基准年第一次缺勤的原因"
label variable causafast2 "工人基准年第二次缺勤的原因"
label variable causafast3 "工人在基准年第三次缺勤的原因"
label variable diainiaf1 "第一次休假的开始日期"
label variable diainiaf2 "第二次休假的开始日期"
label variable diainiaf3 "第三次休假的开始日"
label variable diafimaf1 "第一次休假的结束日期"
label variable diafimaf2 "第二次休假结束日期"
label variable diafimaf3 "第三次休假结束日"
label variable mesiniaf1 "第一次休假开始月份"
label variable mesiniaf2 "第二次休假开始月份"
label variable mesiniaf3 "第三次休假开始月份"
label variable mesfimaf1 "第一次休假结束月份"
label variable mesfimaf2 "第二次休假结束月份"
label variable mesfimaf3 "第三次休假结束月份"
