* Translated Variable Labels for RAIS_2005_collapsed_estab_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year "Année"
label variable n_workers "Nombre de travailleurs (total)"
label variable hired "Nombre d'embauches"
label variable laid_off "Nombre de licenciements"
label variable churn "Baratte"
label variable wage_total "Salaire annuel total ($ R$)"
label variable wage_total_def "Salaire annuel total (R$ 2018)"
label variable wage_avg "Salaire mensuel (R$)"
label variable wage_avg_def "Salaire mensuel (R$ 2018)"
label variable wage_pw "Salaire par travailleur ($ R$)"
label variable wage_def_pw "Salaire par travailleur (R$ 2018)"
