* Translated Variable Labels for RAIS_1995-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year "Année"
label variable n_jobs "Emplois"
label variable wage "Salaires (R$ 2018)"
label variable n_jobs_np "Emplois à but non lucratif"
label variable wage_np "Salaires à but non lucratif (R$ 2018)"
label variable n_jobs_priv "Emplois privés"
label variable wage_priv "Salaires privés (R$ 2018)"
label variable n_jobs_pub_fed_exec "Emplois publics exécutifs fédéraux"
label variable wage_pub_fed_exec "Salaires des cadres fédéraux (R$ 2018)"
label variable n_jobs_pub_fed_jud "Emplois Publics Judiciaires Fédéraux"
label variable wage_pub_fed_jud "Salaires du secteur judiciaire fédéral (R$ 2018)"
label variable n_jobs_pub_fed_leg "Emplois publics législatifs fédéraux"
label variable wage_pub_fed_leg "Salaires publics législatifs fédéraux (R$ 2018)"
label variable n_jobs_pub_mun_exec "Emplois publics exécutifs municipaux"
label variable wage_pub_mun_exec "Salaires des cadres municipaux (R$ 2018)"
label variable n_jobs_pub_mun_jud "Emplois Publics Judiciaires Municipaux"
label variable wage_pub_mun_jud "Salaires du secteur judiciaire municipal (R$ 2018)"
label variable n_jobs_pub_mun_leg "Emplois publics législatifs municipaux"
label variable wage_pub_mun_leg "Salaires publics législatifs municipaux (R$ 2018)"
label variable n_jobs_pub_stt_exec "Emplois publics exécutifs de l’État"
label variable wage_pub_stt_exec "Salaires des cadres de l’État (R$ 2018)"
label variable n_jobs_pub_stt_jud "Emplois publics judiciaires d’État"
label variable wage_pub_stt_jud "Salaires du secteur judiciaire de l’État (R$ 2018)"
label variable n_jobs_pub_stt_leg "Emplois publics législatifs de l’État"
label variable wage_pub_stt_leg "Salaires publics législatifs de l’État (R$ 2018)"
label variable n_jobs_np_educ "Emplois dans l'éducation à but non lucratif"
label variable n_jobs_priv_educ "Emplois dans l'enseignement privé"
label variable n_jobs_pub_fed_exec_educ "Emplois chez les cadres fédéraux en éducation publique"
label variable n_jobs_pub_fed_jud_educ "Emplois dans l'enseignement public judiciaire fédéral"
label variable n_jobs_pub_fed_leg_educ "Emplois en Éducation publique législative fédérale"
label variable n_jobs_pub_mun_exec_educ "Emplois pour les cadres municipaux en éducation publique"
label variable n_jobs_pub_mun_jud_educ "Emplois en Éducation publique judiciaire municipale"
label variable n_jobs_pub_mun_leg_educ "Emplois en Éducation publique législative municipale"
label variable n_jobs_pub_stt_exec_educ "Emplois dans l'enseignement public à la direction de l'État"
label variable n_jobs_pub_stt_jud_educ "Emplois dans l'enseignement public judiciaire de l'État"
label variable n_jobs_pub_stt_leg_educ "Emplois dans l'enseignement public législatif de l'État"
label variable wage_np_educ "Salaires de l'éducation à but non lucratif (R$ 2018)"
label variable wage_priv_educ "Salaires de l’enseignement privé (R$ 2018)"
label variable wage_pub_fed_exec_educ "Salaires des cadres fédéraux dans l’enseignement public (R$ 2018)"
label variable wage_pub_fed_jud_educ "Salaires de l’enseignement public de la magistrature fédérale (R$ 2018)"
label variable wage_pub_fed_leg_educ "Salaires de l’enseignement public législatif fédéral (R$ 2018)"
label variable wage_pub_mun_exec_educ "Salaires des cadres municipaux de l’enseignement public (R$ 2018)"
label variable wage_pub_mun_jud_educ "Salaires de l’enseignement public du système judiciaire municipal (R$ 2018)"
label variable wage_pub_mun_leg_educ "Salaires de l’enseignement public législatif municipal (R$ 2018)"
label variable wage_pub_stt_exec_educ "Salaires des cadres de l’enseignement public de l’État (R$ 2018)"
label variable wage_pub_stt_jud_educ "Salaires de l’enseignement public du système judiciaire de l’État (R$ 2018)"
label variable wage_pub_stt_leg_educ "Salaires de l’enseignement public législatif de l’État (R$ 2018)"
label variable n_jobs_np_health "Emplois dans le domaine de la santé à but non lucratif"
label variable n_jobs_priv_health "Emplois dans le secteur privé de la santé"
label variable n_jobs_pub_fed_exec_health "Emplois chez les cadres fédéraux en santé publique"
label variable n_jobs_pub_fed_jud_health "Emplois dans la magistrature fédérale en santé publique"
label variable n_jobs_pub_fed_leg_health "Emplois en santé publique au niveau législatif fédéral"
label variable n_jobs_pub_mun_exec_health "Emplois chez les cadres municipaux en santé publique"
label variable n_jobs_pub_mun_jud_health "Emplois en santé publique judiciaire municipale"
label variable n_jobs_pub_mun_leg_health "Emplois en santé publique législative municipale"
label variable n_jobs_pub_stt_exec_health "Emplois chez les cadres de l'État en santé publique"
label variable n_jobs_pub_stt_jud_health "Emplois en santé publique judiciaire dans l'État"
label variable n_jobs_pub_stt_leg_health "Emplois en santé publique législative de l'État"
label variable wage_np_health "Salaires de santé à but non lucratif (R$ 2018)"
label variable wage_priv_health "Salaires des soins de santé privés (R$ 2018)"
label variable wage_pub_fed_exec_health "Salaires des cadres fédéraux de la santé publique (R$ 2018)"
label variable wage_pub_fed_jud_health "Salaires de la magistrature fédérale en santé publique (R$ 2018)"
label variable wage_pub_fed_leg_health "Salaires législatifs fédéraux en matière de santé publique (R$ 2018)"
label variable wage_pub_mun_exec_health "Salaires des cadres municipaux de la santé publique (R$ 2018)"
label variable wage_pub_mun_jud_health "Salaires de la santé publique du système judiciaire municipal (R$ 2018)"
label variable wage_pub_mun_leg_health "Salaires législatifs municipaux de la santé publique (R$ 2018)"
label variable wage_pub_stt_exec_health "Salaires des cadres de la santé publique (R$ 2018)"
label variable wage_pub_stt_jud_health "Salaires de la santé publique du système judiciaire de l’État (R$ 2018)"
label variable wage_pub_stt_leg_health "Salaires législatifs de la santé publique de l’État (R$ 2018)"
label variable n_estab "Établissements"
label variable n_estab_ag "Établissements : Agriculture"
label variable n_estab_extr "Établissements : Industrie Extractive"
label variable n_estab_transf "Établissements : Industrie de Transformation"
label variable n_estab_EGW "Etablissements : Électricité, Gaz et Eau"
label variable n_estab_constr "Établissements : Construction"
label variable n_estab_comm "Établissements : Communication"
label variable n_estab_TSC "Établissements : Transport, Stockage et Communication"
label variable n_estab_LF "Établissements : Hébergement et Restauration"
label variable n_estab_IC "Etablissements : Information et Communication"
label variable n_estab_fin "Établissements : Finance"
label variable n_estab_real_estate "Établissements : Immobilier"
label variable n_estab_CST "Établissements : bureau, sciences ou techniques"
label variable n_estab_admin "Établissements : Administratif"
label variable n_estab_PADSS "Établissements : Administration Publique, Défense ou Services Sociaux"
label variable n_estab_educ "Établissements : Éducation"
label variable n_estab_HSS "Établissements : Santé ou Services Sociaux"
label variable n_estab_ACS "Établissements : Art, Culture et Sports"
label variable n_estab_OS "Établissements : Autres services"
label variable n_estab_DS "Établissements : Services domestiques"
label variable n_estab_IO "Établissements : Organisations internationales"
label variable n_estab_fishing "Établissements : Pêche"
label variable n_estab_OSS "Établissements : Autres services sociaux"
label variable n_estab_missing "Établissements : disparus"
