* Translated Variable Labels for RAIS_1985-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Commune où est situé l'établissement"
label variable year "Année"
label variable n_jobs "Emplois"
label variable n_educ_workers "Nombre de travailleurs de l'éducation"
label variable n_health_workers "Nombre d'agents de santé"
label variable n_estab "Établissements"
label variable wage_total_def "Salaires (R$ 2018)"
label variable n_jobs_np "Emplois à but non lucratif"
label variable wage_total_def_np "Salaires à but non lucratif (R$ 2018)"
label variable n_jobs_priv "Emplois privés"
label variable wage_total_def_priv "Salaires privés (R$ 2018)"
label variable n_jobs_pub_fed_exec "Emplois publics exécutifs fédéraux"
label variable wage_total_def_pub_fed_exec "Salaires des cadres fédéraux (R$ 2018)"
label variable n_jobs_pub_fed_jud "Emplois Publics Judiciaires Fédéraux"
label variable wage_total_def_pub_fed_jud "Salaires du secteur judiciaire fédéral (R$ 2018)"
label variable n_jobs_pub_fed_leg "Emplois publics législatifs fédéraux"
label variable wage_total_def_pub_fed_leg "Salaires publics législatifs fédéraux (R$ 2018)"
label variable n_jobs_pub_mun_exec "Emplois publics exécutifs municipaux"
label variable wage_total_def_pub_mun_exec "Salaires des cadres municipaux (R$ 2018)"
label variable n_jobs_pub_mun_jud "Emplois Publics Judiciaires Municipaux"
label variable wage_total_def_pub_mun_jud "Salaires du secteur judiciaire municipal (R$ 2018)"
label variable n_jobs_pub_mun_leg "Emplois publics législatifs municipaux"
label variable wage_total_def_pub_mun_leg "Salaires publics législatifs municipaux (R$ 2018)"
label variable n_jobs_pub_stt_exec "Emplois publics exécutifs de l’État"
label variable wage_total_def_pub_stt_exec "Salaires des cadres de l’État (R$ 2018)"
label variable n_jobs_pub_stt_jud "Emplois publics judiciaires d’État"
label variable wage_total_def_pub_stt_jud "Salaires du secteur judiciaire de l’État (R$ 2018)"
label variable n_jobs_pub_stt_leg "Emplois publics législatifs de l’État"
label variable wage_total_def_pub_stt_leg "Salaires publics législatifs de l’État (R$ 2018)"
