* Translated Variable Labels for RAIS_1987.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Numéro d’inscription du salarié au registre PIS/PASEP"
label variable identificad "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable radiccnpj "Radical du CNPJ de l'establishment (8 positions, sans zéros à gauche)"
label variable municipio "Commune où est situé l'établissement"
label variable uf "Unité de la Fédération"
label variable tpvinculo "Type de relation de travail"
label variable sitvinculo "Statut des obligations"
label variable empem3112 "Indicateur de lien actif au 31/12 (1 - oui ; 0 - non)"
label variable anoadm "Année d'admission"
label variable mesadmissao "Mois d'embauche du travailleur"
label variable causadesli "Cause de l'arrêt"
label variable mesdesli "Mois de cessation d'emploi du salarié"
label variable ocupacao94 "CBO (Classification Brésilienne des Professions), créée en 1994"
label variable grinstrucao "Degré d'enseignement"
label variable genero "Genre"
label variable faixaetaria "Tranche d'âge"
label variable nacionalidad "Nationalité"
label variable remdezembro "Rémunération des travailleurs en décembre, en salaire minimum"
label variable remmedia "Salaire moyen de l'année en SMIC"
label variable tempempr "La durée d'emploi du travailleur en mois (une fois accumulée, elle représente la somme des"
label variable tamestab "Taille de l'établissement - Salariés actifs au 31/12"
label variable tipoestbl "Type d'établissement déclarant (CNPJ, CEI, Non Identifié ou Ignoré)"
label variable ibgesubsetor "Sous-secteur IBGE de l'établissement"
label variable ibgeatividade "Activité IBGE de l'établissement"
label variable bairrossp "Quartiers SP"
label variable distritossp "Districts SP"
