* Translated Variable Labels for RAIS_2005.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Numéro d’inscription du salarié au registre PIS/PASEP"
label variable CPF "CPF du travailleur"
label variable numectps "Numéro CTPS du travailleur"
label variable nome "Nom du travailleur"
label variable identificad "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable radiccnpj "Radical du CNPJ de l'establishment (8 positions, sans zéros à gauche)"
label variable municipio "Commune où est situé l'établissement"
label variable tpvinculo "Type de relation de travail"
label variable empem3112 "Indicateur de lien actif au 31/12 (1 - oui ; 0 - non)"
label variable tipoadm "RECODE du tipoadm (TYPE ADM)"
label variable dtadmissao "Date d'admission du travailleur (Complet)"
label variable causadesli "Cause de l'arrêt"
label variable diadesli "Journée de licenciement des travailleurs"
label variable mesdesli "Mois de cessation d'emploi du salarié"
label variable ocupacao94 "CBO (Classification Brésilienne des Professions), créée en 1994"
label variable ocup2002 "CBO (Classification Brésilienne des Professions), créée en 2002 (6 chiffres)"
label variable grinstrucao "Degré d'enseignement"
label variable genero "Genre"
label variable dtnascimento "Date de naissance du travailleur"
label variable nacionalidad "Nationalité"
label variable portdefic "N'a pas de handicap"
label variable raca_cor "Race et couleur du travailleur"
label variable remdezembro "Rémunération des travailleurs en décembre, en salaire minimum"
label variable remdezr "Rémunération moyenne des travailleurs en décembre, en valeur nominale"
label variable remmedia "Salaire moyen de l'année en SMIC"
label variable remmedr "Salaire moyen de l'année en valeur nominale"
label variable tempempr "La durée d'emploi du travailleur en mois (une fois accumulée, elle représente la somme des"
label variable tiposal "Type de contrat"
label variable salcontr "Le salaire contractuel du travailleur, en valeur nominale"
label variable ultrem ""
label variable horascontr "Nombre d'heures contractuelles par semaine"
label variable clascnae95 "CNAE Classe 1.0 (activité principale de l'établissement)"
label variable tamestab "Taille de l'établissement - Salariés actifs au 31/12"
label variable natjuridica "Nature juridique de l'établissement"
label variable tipoestbl "Type d'établissement déclarant (CNPJ, CEI, Non Identifié ou Ignoré)"
label variable indceivinc "Indicateur d'établissement avec CEI lié"
label variable ceivinc "Numéro CEI lié, le cas échéant"
label variable indalvara "Indicateur de travailleur avec permis judiciaire"
label variable indpat "Indicateur d'établissement appartenant au PAT"
label variable indsimples "Indicateur d'option SIMPLES"
