* Translated Variable Labels for RAIS_estab_in_split_AMC_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable year "Año"
label variable id_munic_6_m1 "Municipio donde está ubicado el establecimiento"
label variable id_AMC_m1 "Identificación AMC 1991-2010"
label variable state_abbrev_m1 "abreviatura del estado"
label variable id_state_m1 "DNI - Estado"
label variable n_new "Número de solicitantes divididos"
label variable n_old "Número de otros divididos"
label variable n_almost_new "Número de solicitantes casi divididos"
label variable n_almost_old "Número de otros casi divididos"
label variable split "Dividir"
label variable almost_split "Casi dividido"
label variable year_split "Año Primera División"
label variable year_almost_split "Primer año casi dividido"
label variable split1993 ""
label variable split1997 ""
label variable split2001 ""
label variable split2005 ""
label variable split2009 ""
label variable n_splits "Número de divisiones"
label variable in_sample "En la muestra"
label variable in_sample_97 "En la muestra"
label variable almost_split_states "Estados con datos casi divididos"
label variable id_munic_6 "Municipio donde está ubicado el establecimiento"
label variable n_workers "Número de trabajadores (total)"
label variable hired "Número de contrataciones"
label variable laid_off "Número de despidos"
label variable churn "Batir"
label variable wage_total "Salario total anual (R$)"
label variable wage_avg "Salario mensual (R$)"
label variable wage_pw "Salario por Trabajador (R$)"
label variable wage_total_def "Salario total anual (R$ 2018)"
label variable wage_avg_def "Salario mensual (R$ 2018)"
label variable wage_def_pw "Salario por Trabajador (R$ 2018)"
label variable diff_munic "Municipio Diferente"
label variable incumbent_new_munic "Titular en Nuevos Municipios"
label variable post "Correo"
label variable tau "tau"
label variable active "Activo"
