* Translated Variable Labels for RAIS_estab_in_split_AMC_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ ou CEI de l'établissement (sans zéros non significatifs)"
label variable year "Année"
label variable id_munic_6_m1 "Commune où est situé l'établissement"
label variable id_AMC_m1 "Numéro d'identification AMC 1991-2010"
label variable state_abbrev_m1 "abréviation d'état"
label variable id_state_m1 "Pièce d'identité - État"
label variable n_new "Nombre de candidats divisés"
label variable n_old "Nombre de fractionnés Autres"
label variable n_almost_new "Nombre de candidats presque divisés"
label variable n_almost_old "Nombre d'autres presque divisés"
label variable split "Diviser"
label variable almost_split "Presque divisé"
label variable year_split "Première division de l'année"
label variable year_almost_split "Première année presque divisée"
label variable split1993 ""
label variable split1997 ""
label variable split2001 ""
label variable split2005 ""
label variable split2009 ""
label variable n_splits "Nombre de divisions"
label variable in_sample "Dans l'échantillon"
label variable in_sample_97 "Dans l'échantillon"
label variable almost_split_states "États avec des données presque divisées"
label variable id_munic_6 "Commune où est situé l'établissement"
label variable n_workers "Nombre de travailleurs (total)"
label variable hired "Nombre d'embauches"
label variable laid_off "Nombre de licenciements"
label variable churn "Baratte"
label variable wage_total "Salaire annuel total ($ R$)"
label variable wage_avg "Salaire mensuel (R$)"
label variable wage_pw "Salaire par travailleur ($ R$)"
label variable wage_total_def "Salaire annuel total (R$ 2018)"
label variable wage_avg_def "Salaire mensuel (R$ 2018)"
label variable wage_def_pw "Salaire par travailleur (R$ 2018)"
label variable diff_munic "Commune différente"
label variable incumbent_new_munic "Titulaire dans les nouvelles municipalités"
label variable post "Poste"
label variable tau "Tau"
label variable active "Actif"
