* Translated Variable Labels for RAIS_estab_in_split_AMC_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "प्रतिष्ठान का सीएनपीजे या सीईआई (अग्रणी शून्य के बिना)"
label variable year "वर्ष"
label variable id_munic_6_m1 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable id_AMC_m1 "एएमसी आईडी 1991-2010"
label variable state_abbrev_m1 "राज्य संक्षिप्तीकरण"
label variable id_state_m1 "आईडी - राज्य"
label variable n_new "विभाजित आवेदकों की संख्या"
label variable n_old "विभाजित अन्य की संख्या"
label variable n_almost_new "लगभग विभाजित आवेदकों की संख्या"
label variable n_almost_old "लगभग विभाजित अन्य लोगों की संख्या"
label variable split "विभाजित करना"
label variable almost_split "लगभग विभाजित"
label variable year_split "वर्ष प्रथम विभाजन"
label variable year_almost_split "वर्ष प्रथम लगभग विभाजित"
label variable split1993 ""
label variable split1997 ""
label variable split2001 ""
label variable split2005 ""
label variable split2009 ""
label variable n_splits "विभाजन की संख्या"
label variable in_sample "नमूने में"
label variable in_sample_97 "नमूने में"
label variable almost_split_states "लगभग विभाजित डेटा वाले राज्य"
label variable id_munic_6 "नगर पालिका जहां प्रतिष्ठान स्थित है"
label variable n_workers "श्रमिकों की संख्या (कुल)"
label variable hired "नियुक्तियों की संख्या"
label variable laid_off "छँटनी की संख्या"
label variable churn "मंथन"
label variable wage_total "कुल वार्षिक वेतन (R$)"
label variable wage_avg "मासिक वेतन (R$)"
label variable wage_pw "प्रति श्रमिक वेतन (R$)"
label variable wage_total_def "कुल वार्षिक वेतन (R$2018)"
label variable wage_avg_def "मासिक वेतन (R$2018)"
label variable wage_def_pw "प्रति श्रमिक वेतन (R$ 2018)"
label variable diff_munic "अलग-अलग नगर पालिका"
label variable incumbent_new_munic "नई नगर पालिकाओं में पदधारी"
label variable post "डाक"
label variable tau "ताउ"
label variable active "सक्रिय"
