* Translated Variable Labels for RAIS_1995-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable n_jobs "Jobs"
label variable wage "Wages (R$ 2018)"
label variable n_jobs_np "Non-Profit Jobs"
label variable wage_np "Non-Profit Wages (R$ 2018)"
label variable n_jobs_priv "Private Jobs"
label variable wage_priv "Private Wages (R$ 2018)"
label variable n_jobs_pub_fed_exec "Federal Executive Public Jobs"
label variable wage_pub_fed_exec "Federal Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_fed_jud "Federal Judicial Public Jobs"
label variable wage_pub_fed_jud "Federal Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_fed_leg "Federal Legislative Public Jobs"
label variable wage_pub_fed_leg "Federal Legislative Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_exec "Municipal Executive Public Jobs"
label variable wage_pub_mun_exec "Municipal Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_jud "Municipal Judicial Public Jobs"
label variable wage_pub_mun_jud "Municipal Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_leg "Municipal Legislative Public Jobs"
label variable wage_pub_mun_leg "Municipal Legislative Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_exec "State Executive Public Jobs"
label variable wage_pub_stt_exec "State Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_jud "State Judicial Public Jobs"
label variable wage_pub_stt_jud "State Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_leg "State Legislative Public Jobs"
label variable wage_pub_stt_leg "State Legislative Public Wages (R$ 2018)"
label variable n_jobs_np_educ "Non-Profit Education Jobs"
label variable n_jobs_priv_educ "Private Education Jobs"
label variable n_jobs_pub_fed_exec_educ "Federal Executive Public Education Jobs"
label variable n_jobs_pub_fed_jud_educ "Federal Judicial Public Education Jobs"
label variable n_jobs_pub_fed_leg_educ "Federal Legislative Public Education Jobs"
label variable n_jobs_pub_mun_exec_educ "Municipal Executive Public Education Jobs"
label variable n_jobs_pub_mun_jud_educ "Municipal Judicial Public Education Jobs"
label variable n_jobs_pub_mun_leg_educ "Municipal Legislative Public Education Jobs"
label variable n_jobs_pub_stt_exec_educ "State Executive Public Education Jobs"
label variable n_jobs_pub_stt_jud_educ "State Judicial Public Education Jobs"
label variable n_jobs_pub_stt_leg_educ "State Legislative Public Education Jobs"
label variable wage_np_educ "Non-Profit Education Wages (R$ 2018)"
label variable wage_priv_educ "Private Education Wages (R$ 2018)"
label variable wage_pub_fed_exec_educ "Federal Executive Public Education Wages (R$ 2018)"
label variable wage_pub_fed_jud_educ "Federal Judiciary Public Education Wages (R$ 2018)"
label variable wage_pub_fed_leg_educ "Federal Legislative Public Education Wages (R$ 2018)"
label variable wage_pub_mun_exec_educ "Municipal Executive Public Education Wages (R$ 2018)"
label variable wage_pub_mun_jud_educ "Municipal Judiciary Public Education Wages (R$ 2018)"
label variable wage_pub_mun_leg_educ "Municipal Legislative Public Education Wages (R$ 2018)"
label variable wage_pub_stt_exec_educ "State Executive Public Education Wages (R$ 2018)"
label variable wage_pub_stt_jud_educ "State Judiciary Public Education Wages (R$ 2018)"
label variable wage_pub_stt_leg_educ "State Legislative Public Education Wages (R$ 2018)"
label variable n_jobs_np_health "Non-Profit Health Jobs"
label variable n_jobs_priv_health "Private Health Jobs"
label variable n_jobs_pub_fed_exec_health "Federal Executive Public Health Jobs"
label variable n_jobs_pub_fed_jud_health "Federal Judicial Public Health Jobs"
label variable n_jobs_pub_fed_leg_health "Federal Legislative Public Health Jobs"
label variable n_jobs_pub_mun_exec_health "Municipal Executive Public Health Jobs"
label variable n_jobs_pub_mun_jud_health "Municipal Judicial Public Health Jobs"
label variable n_jobs_pub_mun_leg_health "Municipal Legislative Public Health Jobs"
label variable n_jobs_pub_stt_exec_health "State Executive Public Health Jobs"
label variable n_jobs_pub_stt_jud_health "State Judicial Public Health Jobs"
label variable n_jobs_pub_stt_leg_health "State Legislative Public Health Jobs"
label variable wage_np_health "Non-Profit Health Wages (R$ 2018)"
label variable wage_priv_health "Private Health Wages (R$ 2018)"
label variable wage_pub_fed_exec_health "Federal Executive Public Health Wages (R$ 2018)"
label variable wage_pub_fed_jud_health "Federal Judiciary Public Health Wages (R$ 2018)"
label variable wage_pub_fed_leg_health "Federal Legislative Public Health Wages (R$ 2018)"
label variable wage_pub_mun_exec_health "Municipal Executive Public Health Wages (R$ 2018)"
label variable wage_pub_mun_jud_health "Municipal Judiciary Public Health Wages (R$ 2018)"
label variable wage_pub_mun_leg_health "Municipal Legislative Public Health Wages (R$ 2018)"
label variable wage_pub_stt_exec_health "State Executive Public Health Wages (R$ 2018)"
label variable wage_pub_stt_jud_health "State Judiciary Public Health Wages (R$ 2018)"
label variable wage_pub_stt_leg_health "State Legislative Public Health Wages (R$ 2018)"
label variable n_estab "Establishments"
label variable n_estab_ag "Establishments: Agriculture"
label variable n_estab_extr "Establishments: Extractive Industry"
label variable n_estab_transf "Establishments: Transformation Industry"
label variable n_estab_EGW "Establishments: Electricity, Gas and Water"
label variable n_estab_constr "Establishments: Construction"
label variable n_estab_comm "Establishments: Communication"
label variable n_estab_TSC "Establishments: Transportation, Storage and Communication"
label variable n_estab_LF "Establishments: Lodging and Food"
label variable n_estab_IC "Establishments: Information and Communication"
label variable n_estab_fin "Establishments: Finance"
label variable n_estab_real_estate "Establishments: Real Estate"
label variable n_estab_CST "Establishments: Clerical, Science or Technical"
label variable n_estab_admin "Establishments: Administrative"
label variable n_estab_PADSS "Establishments: Public Administration, Defense or Social Services"
label variable n_estab_educ "Establishments: Education"
label variable n_estab_HSS "Establishments: Health or Social Services"
label variable n_estab_ACS "Establishments: Art, Culture and Sports"
label variable n_estab_OS "Establishments: Other Services"
label variable n_estab_DS "Establishments: Domestic Services"
label variable n_estab_IO "Establishments: International Organizations"
label variable n_estab_fishing "Establishments: Fishing"
label variable n_estab_OSS "Establishments: Other Social Services"
label variable n_estab_missing "Establishments: Missing"
