* Translated Variable Labels for RAIS_1985-2018_collapsed_estab_munic_sample5.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ or CEI of the establishment (without leading zeros)"
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable n_workers "Number of Workers (Total)"
label variable hired "Number of Hires"
label variable laid_off "Number of Layoffs"
label variable churn "Churn"
label variable wage_total "Total Yearly Wage (R$)"
label variable wage_avg "Monthly Wage (R$)"
label variable wage_pw "Wage per Worker (R$)"
label variable wage_total_def "Total Yearly Wage (R$ 2018)"
label variable wage_avg_def "Monthly Wage (R$ 2018)"
label variable wage_def_pw "Wage per Worker (R$ 2018)"
