* Translated Variable Labels for RAIS_1985-2018_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable n_jobs "Jobs"
label variable n_educ_workers "Number of Education Workers"
label variable n_health_workers "Number of Health Workers"
label variable n_estab "Establishments"
label variable wage_total_def "Wages (R$ 2018)"
label variable n_jobs_np "Non-Profit Jobs"
label variable wage_total_def_np "Non-Profit Wages (R$ 2018)"
label variable n_jobs_priv "Private Jobs"
label variable wage_total_def_priv "Private Wages (R$ 2018)"
label variable n_jobs_pub_fed_exec "Federal Executive Public Jobs"
label variable wage_total_def_pub_fed_exec "Federal Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_fed_jud "Federal Judicial Public Jobs"
label variable wage_total_def_pub_fed_jud "Federal Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_fed_leg "Federal Legislative Public Jobs"
label variable wage_total_def_pub_fed_leg "Federal Legislative Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_exec "Municipal Executive Public Jobs"
label variable wage_total_def_pub_mun_exec "Municipal Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_jud "Municipal Judicial Public Jobs"
label variable wage_total_def_pub_mun_jud "Municipal Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_leg "Municipal Legislative Public Jobs"
label variable wage_total_def_pub_mun_leg "Municipal Legislative Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_exec "State Executive Public Jobs"
label variable wage_total_def_pub_stt_exec "State Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_jud "State Judicial Public Jobs"
label variable wage_total_def_pub_stt_jud "State Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_leg "State Legislative Public Jobs"
label variable wage_total_def_pub_stt_leg "State Legislative Public Wages (R$ 2018)"
