* Translated Variable Labels for RAIS_1995-2018_collapsed_munic.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_munic_6 "Municipality where the establishment is located"
label variable year "Year"
label variable n_jobs "Jobs"
label variable wage "Wages (R$ 2018)"
label variable n_jobs_np "Non-Profit Jobs"
label variable wage_np "Non-Profit Wages (R$ 2018)"
label variable n_jobs_priv "Private Jobs"
label variable wage_priv "Private Wages (R$ 2018)"
label variable n_jobs_pub_fed_exec "Federal Executive Public Jobs"
label variable wage_pub_fed_exec "Federal Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_fed_jud "Federal Judicial Public Jobs"
label variable wage_pub_fed_jud "Federal Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_fed_leg "Federal Legislative Public Jobs"
label variable wage_pub_fed_leg "Federal Legislative Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_exec "Municipal Executive Public Jobs"
label variable wage_pub_mun_exec "Municipal Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_jud "Municipal Judicial Public Jobs"
label variable wage_pub_mun_jud "Municipal Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_mun_leg "Municipal Legislative Public Jobs"
label variable wage_pub_mun_leg "Municipal Legislative Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_exec "State Executive Public Jobs"
label variable wage_pub_stt_exec "State Executive Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_jud "State Judicial Public Jobs"
label variable wage_pub_stt_jud "State Judiciary Public Wages (R$ 2018)"
label variable n_jobs_pub_stt_leg "State Legislative Public Jobs"
label variable wage_pub_stt_leg "State Legislative Public Wages (R$ 2018)"
label variable n_jobs_agric "Jobs: Agriculture"
label variable n_jobs_OMM "Jobs: Oil, Mining and Metals"
label variable n_jobs_manuf "Jobs: Manufacturing"
label variable n_jobs_constr "Jobs: Construction"
label variable n_jobs_retail "Jobs: Retail"
label variable n_jobs_other_serv "Jobs: Other Services"
label variable n_jobs_gov "Jobs: Government"
label variable n_jobs_IO "Jobs: Information and Communication"
label variable n_jobs_missing "Jobs: Missing"
label variable wage_avg "(sum) wage_avg"
label variable wage_dec "(sum) wage_dec"
label variable wage_total "(sum) wage_total"
label variable wage_avg_def "(sum) wage_avg_def"
label variable wage_dec_def "(sum) wage_dec_def"
label variable wage_agric "Wages (R$ 2018): Agriculture"
label variable wage_OMM "Wages (R$ 2018): Oil, Mining and Metals"
label variable wage_manuf "Wages (R$ 2018): Manufacturing"
label variable wage_constr "Wages (R$ 2018): Construction"
label variable wage_retail "Wages (R$ 2018): Retail"
label variable wage_other_serv "Wages (R$ 2018): Other Services"
label variable wage_gov "Wages (R$ 2018): Government"
label variable wage_IO "Wages (R$ 2018): Information and Communication"
label variable wage_missing "Wages (R$ 2018): Missing"
label variable n_jobs_np_educ "Non-Profit Education Jobs"
label variable n_jobs_priv_educ "Private Education Jobs"
label variable n_jobs_pub_fed_exec_educ "Federal Executive Public Education Jobs"
label variable n_jobs_pub_fed_jud_educ "Federal Judicial Public Education Jobs"
label variable n_jobs_pub_fed_leg_educ "Federal Legislative Public Education Jobs"
label variable n_jobs_pub_mun_exec_educ "Municipal Executive Public Education Jobs"
label variable n_jobs_pub_mun_jud_educ "Municipal Judicial Public Education Jobs"
label variable n_jobs_pub_mun_leg_educ "Municipal Legislative Public Education Jobs"
label variable n_jobs_pub_stt_exec_educ "State Executive Public Education Jobs"
label variable n_jobs_pub_stt_jud_educ "State Judicial Public Education Jobs"
label variable n_jobs_pub_stt_leg_educ "State Legislative Public Education Jobs"
label variable wage_np_educ "Non-Profit Education Wages (R$ 2018)"
label variable wage_priv_educ "Private Education Wages (R$ 2018)"
label variable wage_pub_fed_exec_educ "Federal Executive Public Education Wages (R$ 2018)"
label variable wage_pub_fed_jud_educ "Federal Judiciary Public Education Wages (R$ 2018)"
label variable wage_pub_fed_leg_educ "Federal Legislative Public Education Wages (R$ 2018)"
label variable wage_pub_mun_exec_educ "Municipal Executive Public Education Wages (R$ 2018)"
label variable wage_pub_mun_jud_educ "Municipal Judiciary Public Education Wages (R$ 2018)"
label variable wage_pub_mun_leg_educ "Municipal Legislative Public Education Wages (R$ 2018)"
label variable wage_pub_stt_exec_educ "State Executive Public Education Wages (R$ 2018)"
label variable wage_pub_stt_jud_educ "State Judiciary Public Education Wages (R$ 2018)"
label variable wage_pub_stt_leg_educ "State Legislative Public Education Wages (R$ 2018)"
label variable n_jobs_np_health "Non-Profit Health Jobs"
label variable n_jobs_priv_health "Private Health Jobs"
label variable n_jobs_pub_fed_exec_health "Federal Executive Public Health Jobs"
label variable n_jobs_pub_fed_jud_health "Federal Judicial Public Health Jobs"
label variable n_jobs_pub_fed_leg_health "Federal Legislative Public Health Jobs"
label variable n_jobs_pub_mun_exec_health "Municipal Executive Public Health Jobs"
label variable n_jobs_pub_mun_jud_health "Municipal Judicial Public Health Jobs"
label variable n_jobs_pub_mun_leg_health "Municipal Legislative Public Health Jobs"
label variable n_jobs_pub_stt_exec_health "State Executive Public Health Jobs"
label variable n_jobs_pub_stt_jud_health "State Judicial Public Health Jobs"
label variable n_jobs_pub_stt_leg_health "State Legislative Public Health Jobs"
label variable wage_np_health "Non-Profit Health Wages (R$ 2018)"
label variable wage_priv_health "Private Health Wages (R$ 2018)"
label variable wage_pub_fed_exec_health "Federal Executive Public Health Wages (R$ 2018)"
label variable wage_pub_fed_jud_health "Federal Judiciary Public Health Wages (R$ 2018)"
label variable wage_pub_fed_leg_health "Federal Legislative Public Health Wages (R$ 2018)"
label variable wage_pub_mun_exec_health "Municipal Executive Public Health Wages (R$ 2018)"
label variable wage_pub_mun_jud_health "Municipal Judiciary Public Health Wages (R$ 2018)"
label variable wage_pub_mun_leg_health "Municipal Legislative Public Health Wages (R$ 2018)"
label variable wage_pub_stt_exec_health "State Executive Public Health Wages (R$ 2018)"
label variable wage_pub_stt_jud_health "State Judiciary Public Health Wages (R$ 2018)"
label variable wage_pub_stt_leg_health "State Legislative Public Health Wages (R$ 2018)"
label variable n_estab "Establishments"
label variable n_estab_agric "Establishments: Agriculture"
label variable n_estab_OMM "Establishments: Oil, Mining and Metals"
label variable n_estab_manuf "Establishments: Manufacturing"
label variable n_estab_constr "Establishments: Construction"
label variable n_estab_retail "Establishments: Retail"
label variable n_estab_other_serv "Establishments: Other Services"
label variable n_estab_gov "Establishments: Government"
label variable n_estab_IO "Establishments: Information and Communication"
label variable n_estab_missing "Establishments: Missing"
