* Translated Variable Labels for RAIS_1985.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Número de registro de empleado en el Registro PIS/PASEP"
label variable identificad "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable radiccnpj "Radical del CNPJ del establishment (8 posiciones, sin ceros a la izquierda)"
label variable municipio "Municipio donde está ubicado el establecimiento"
label variable uf "unidad de la federación"
label variable tpvinculo "Tipo de relación laboral"
label variable sitvinculo "Estado del bono"
label variable empem3112 "Indicador de enlace activo el 31/12 (1 - sí; 0 - no)"
label variable anoadm "Año de admisión"
label variable mesadmissao "Mes de contratación del trabajador"
label variable causadesli "Causa del cierre"
label variable mesdesli "Mes de despido del empleado"
label variable ocupacao94 "CBO (Clasificación Brasileña de Ocupaciones), creada en 1994"
label variable grinstrucao "Grado de instrucción"
label variable genero "Género"
label variable faixaetaria "Rango de edad"
label variable nacionalidad "Nacionalidad"
label variable remdezembro "Remuneración de los trabajadores en diciembre, en salarios mínimos"
label variable remmedia "Salario promedio del año en salarios mínimos"
label variable tempempr "La duración del empleo del trabajador en meses (cuando se acumula, representa la suma de"
label variable tamestab "Tamaño del establecimiento - Empleados activos al 31/12"
label variable tipoestbl "Tipo de establecimiento declarante (CNPJ, CEI, No Identificado o Ignorado)"
label variable ibgesubsetor "Subsector IBGE del establecimiento."
label variable ibgeatividade "IBGE actividad del establecimiento"
label variable bairrossp "Barrios de SP"
label variable distritossp "Distritos SP"
