* Translated Variable Labels for RAIS_2015.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Número de registro de empleado en el Registro PIS/PASEP"
label variable CPF "CPF del trabajador"
label variable numectps "Número CTPS del trabajador"
label variable nome "nombre del trabajador"
label variable identificad "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable radiccnpj "Radical del CNPJ del establishment (8 posiciones, sin ceros a la izquierda)"
label variable municipio "Municipio donde está ubicado el establecimiento"
label variable tpvinculo "Tipo de relación laboral"
label variable empem3112 "Indicador de enlace activo el 31/12 (1 - sí; 0 - no)"
label variable tipoadm "RECODE oftipadm (Tipo de Admisión)"
label variable dtadmissao "Fecha de ingreso del trabajador (Completo)"
label variable causadesli "Causa del cierre"
label variable diadesli "día del despido del trabajador"
label variable mesdesli "Mes de despido del empleado"
label variable ocup2002 "CBO (Clasificación Brasileña de Ocupaciones), creada en 2002 (6 dígitos)"
label variable grinstrucao "Grado de instrucción"
label variable genero "Género"
label variable dtnascimento "fecha de nacimiento del trabajador"
label variable idade ""
label variable nacionalidad "Nacionalidad"
label variable portdefic "No tiene discapacidad"
label variable tpdefic "Tipo de discapacidad"
label variable raca_cor "Raza y color del trabajador."
label variable remdezembro "Remuneración de los trabajadores en diciembre, en salarios mínimos"
label variable remdezr "Remuneración media de los trabajadores en diciembre, en valor nominal"
label variable remmedia "Salario promedio del año en salarios mínimos"
label variable remmedr "Salario medio del año en valor nominal"
label variable tempempr "La duración del empleo del trabajador en meses (cuando se acumula, representa la suma de"
label variable tiposal "Tipo de contrato Salario"
label variable salcontr "El salario contractual del trabajador, en valor nominal"
label variable ultrem ""
label variable horascontr "Número de horas contractuales por semana"
label variable sbclas20 "Grupo de actividades económicas, según clasificación CNAE 2.0"
label variable clascnae95 "CNAE Clase 1.0 (actividad principal del establecimiento)"
label variable clascnae20 "CNAE Clase 2.0 (actividad principal del establecimiento)"
label variable tamestab "Tamaño del establecimiento - Empleados activos al 31/12"
label variable natjuridica "Naturaleza jurídica del establecimiento"
label variable tipoestbl "Tipo de establecimiento declarante (CNPJ, CEI, No Identificado o Ignorado)"
label variable indceivinc "Indicador de establecimiento con CEI vinculado"
label variable ceivinc "Número CEI vinculado, si lo hubiera"
label variable indalvara "Indicador de trabajador con Permiso Judicial"
label variable indpat "Indicador de establecimiento perteneciente al PAT"
label variable indsimples "Indicador de opción SIMPLES"
label variable ocupacao94 "Ocupación CBO 94"
label variable qtdiasafas "Número de días de ausencia"
label variable ibgesubsetor "Subsector IBGE"
label variable anochegbr "Año de llegada a Brasil"
label variable cepestab "Establecimiento CEP"
label variable muntrab "Mun Trab"
label variable razaosocial "Razón social"
label variable remjan "Remuneración media de los trabajadores en enero, en valor nominal"
label variable remfev "Remuneración media de los trabajadores en febrero, en valor nominal"
label variable remmar "Remuneración media de los trabajadores en marzo, en valor nominal"
label variable remabr "Remuneración media de los trabajadores en abril, en valor nominal"
label variable remmai "Remuneración media de los trabajadores en mayo, en valor nominal"
label variable remjun "Remuneración media de los trabajadores en junio, en valor nominal"
label variable remjul "Remuneración media de los trabajadores en julio, en valor nominal"
label variable remago "Remuneración media de los trabajadores en agosto, en valor nominal"
label variable remset "Remuneración media de los trabajadores en septiembre, en valor nominal"
label variable remout "Remuneración media de los trabajadores en octubre, en valor nominal"
label variable remnov "Remuneración media de los trabajadores en noviembre, en valor nominal"
label variable causafast1 "Causa de la primera ausencia del trabajador en el año base"
label variable causafast2 "Causa de la segunda ausencia del trabajador en el año base"
label variable causafast3 "Causa de la tercera ausencia del trabajador en el año base"
label variable diainiaf1 "Fecha de inicio de la primera licencia"
label variable diainiaf2 "Fecha de inicio de la segunda baja"
label variable diainiaf3 "Día de inicio de la tercera licencia."
label variable diafimaf1 "Fecha de finalización de la primera licencia"
label variable diafimaf2 "Fecha de finalización de la segunda baja"
label variable diafimaf3 "Día final del tercer permiso"
label variable mesiniaf1 "Mes de inicio de las primeras vacaciones"
label variable mesiniaf2 "Mes de inicio de la segunda baja"
label variable mesiniaf3 "Mes de inicio de la tercera baja"
label variable mesfimaf1 "Mes de finalización del primer permiso"
label variable mesfimaf2 "Mes de fin de la segunda baja"
label variable mesfimaf3 "Mes de fin de la tercera baja"
