* Translated Variable Labels for RAIS_2002.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable PIS "Número de registro de empleado en el Registro PIS/PASEP"
label variable CPF "CPF del trabajador"
label variable nome "nombre del trabajador"
label variable identificad "CNPJ o CEI del establecimiento (sin ceros a la izquierda)"
label variable radiccnpj "Radical del CNPJ del establishment (8 posiciones, sin ceros a la izquierda)"
label variable municipio "Municipio donde está ubicado el establecimiento"
label variable tpvinculo "Tipo de relación laboral"
label variable empem3112 "Indicador de enlace activo el 31/12 (1 - sí; 0 - no)"
label variable dtadmissao "Fecha de ingreso del trabajador (Completo)"
label variable causadesli "Causa del cierre"
label variable mesdesli "Mes de despido del empleado"
label variable ocupacao94 "CBO (Clasificación Brasileña de Ocupaciones), creada en 1994"
label variable grinstrucao "Grado de instrucción"
label variable genero "Género"
label variable dtnascimento "fecha de nacimiento del trabajador"
label variable nacionalidad "Nacionalidad"
label variable remdezembro "Remuneración de los trabajadores en diciembre, en salarios mínimos"
label variable remmedia "Salario promedio del año en salarios mínimos"
label variable remdezr "Remuneración media de los trabajadores en diciembre, en valor nominal"
label variable remmedr "Salario medio del año en valor nominal"
label variable tempempr "La duración del empleo del trabajador en meses (cuando se acumula, representa la suma de"
label variable clascnae95 "CNAE Clase 1.0 (actividad principal del establecimiento)"
label variable tamestab "Tamaño del establecimiento - Empleados activos al 31/12"
label variable tipoestbl "Tipo de establecimiento declarante (CNPJ, CEI, No Identificado o Ignorado)"
label variable natjuridica "Naturaleza jurídica del establecimiento"
label variable indceivinc "Indicador de establecimiento con CEI vinculado"
label variable horascontr "Número de horas contractuales por semana"
label variable numectps "Número CTPS del trabajador"
label variable ceivinc "Número CEI vinculado, si lo hubiera"
label variable tiposal "Tipo de contrato Salario"
label variable salcontr "El salario contractual del trabajador, en valor nominal"
label variable indalvara "Indicador de trabajador con Permiso Judicial"
label variable indpat "Indicador de establecimiento perteneciente al PAT"
label variable indsimples "Indicador de opción SIMPLES"
label variable ultrem ""
label variable TIPOADM "TIPO DE ADM"
