* Translated Variable Labels for RAIS_estab_in_split_AMC_history.dta 
* Author: Aaron Wolf (aaron.wolf@u.northwestern.edu) 
label variable id_estab "CNPJ or CEI of the establishment (without leading zeros)"
label variable year "Year"
label variable id_munic_6_m1 "Municipality where the establishment is located"
label variable id_AMC_m1 "AMC ID 1991-2010"
label variable state_abbrev_m1 "state abbreviation"
label variable id_state_m1 "ID - State"
label variable n_new "Number of Split Applicants"
label variable n_old "Number of Split Others"
label variable n_almost_new "Number of Almost Split Applicants"
label variable n_almost_old "Number of Almost Split Others"
label variable split "Split"
label variable almost_split "Almost Split"
label variable year_split "Year First Split"
label variable year_almost_split "Year First Almost Split"
label variable split1993 ""
label variable split1997 ""
label variable split2001 ""
label variable split2005 ""
label variable split2009 ""
label variable n_splits "Number of Splits"
label variable in_sample "In Sample"
label variable in_sample_97 "In Sample"
label variable almost_split_states "States with Almost Split Data"
label variable id_munic_6 "Municipality where the establishment is located"
label variable n_workers "Number of Workers (Total)"
label variable hired "Number of Hires"
label variable laid_off "Number of Layoffs"
label variable churn "Churn"
label variable wage_total "Total Yearly Wage (R$)"
label variable wage_avg "Monthly Wage (R$)"
label variable wage_pw "Wage per Worker (R$)"
label variable wage_total_def "Total Yearly Wage (R$ 2018)"
label variable wage_avg_def "Monthly Wage (R$ 2018)"
label variable wage_def_pw "Wage per Worker (R$ 2018)"
label variable diff_munic "Different Municipality"
label variable incumbent_new_munic "Incumbent in New Municipalities"
label variable post "Post"
label variable tau "Tau"
label variable active "Active"
